// Code generated by ./startup/internal/cmd/generate; DO NOT EDIT.
// Raw wasm exports so the Go module's //go:wasmimport bindings resolve
// without a JS trampoline. 64-bit values arrive as (hi, lo) uint32 pairs
// matching the UINT64()/INT64() macros; strings as (address, length) into
// engine memory.
#include <string>

static std::string wasm_gd_string_arg(uint32_t addr, uint32_t len) {
    return len ? std::string((const char *)(uintptr_t)addr, (size_t)len) : std::string();
}

extern "C" {
EMSCRIPTEN_KEEPALIVE void wasm_gd_array_get(uint32_t p0, int32_t p1, uint32_t p2) { gd_array_get(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_array_set(uint32_t p0, int32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { gd_array_set(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_builtin_name(uint32_t p0, uint32_t p1, uint32_t p2) { return (uint32_t)gd_builtin_name(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_builtin_call(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_builtin_call(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_name(uint32_t p0) { return (uint32_t)gd_variant_type_name(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_make(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3, uint32_t p4) { gd_variant_type_make(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_call(uint32_t p0, uint32_t p1, uint32_t p2, int32_t p3, uint32_t p4, uint32_t p5) { gd_variant_type_call(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_convertable(uint32_t p0, uint32_t p1, uint32_t p2) { return gd_variant_type_convertable(p0, p1, p2) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_setup_array(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8) { gd_variant_type_setup_array(p0, p1, p2, p3, p4, p5, p6, p7, p8); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_setup_dictionary(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12, uint32_t p13, uint32_t p14, uint32_t p15, uint32_t p16) { gd_variant_type_setup_dictionary(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_fetch_constant(uint32_t p0, uint32_t p1, uint32_t p2) { gd_variant_type_fetch_constant(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_unsafe_constructor(uint32_t p0, int32_t p1) { return (uint32_t)gd_variant_type_unsafe_constructor(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_evaluator(uint32_t p0, uint32_t p1, uint32_t p2) { return (uint32_t)gd_variant_type_evaluator(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_setter(uint32_t p0, uint32_t p1) { return (uint32_t)gd_variant_type_setter(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_getter(uint32_t p0, uint32_t p1) { return (uint32_t)gd_variant_type_getter(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_has_property(uint32_t p0, uint32_t p1) { return gd_variant_type_has_property(p0, p1) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type_builtin_method(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { return (uint32_t)gd_variant_type_builtin_method(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_unsafe_call(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { gd_variant_type_unsafe_call(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_unsafe_make(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_type_unsafe_make(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_type_unsafe_free(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_variant_type_unsafe_free(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_callable_create(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_callable_create(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_callable_lookup(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { return (uint32_t)gd_callable_lookup(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_FileAccess_write(uint32_t p0, uint32_t p1, int32_t p2) { gd_classdb_FileAccess_write(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_classdb_FileAccess_read(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_classdb_FileAccess_read(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_classdb_Image_unsafe(uint32_t p0) { return (uint32_t)gd_classdb_Image_unsafe(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_classdb_Image_access(uint32_t p0, int32_t p1) { return (uint32_t)gd_classdb_Image_access(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_method_list_make(int32_t p0) { return (uint32_t)gd_method_list_make(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_method_list_push(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, int32_t p6, uint32_t p7) { gd_method_list_push(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_method_list_free(uint32_t p0) { gd_method_list_free(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_list_make(int32_t p0) { return (uint32_t)gd_property_list_make(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_property_list_push(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { gd_property_list_push(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_property_list_free(uint32_t p0) { gd_property_list_free(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_type(uint32_t p0) { return (uint32_t)gd_property_info_type(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_name(uint32_t p0) { return (uint32_t)gd_property_info_name(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_class_name(uint32_t p0) { return (uint32_t)gd_property_info_class_name(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_hint(uint32_t p0) { return (uint32_t)gd_property_info_hint(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_hint_string(uint32_t p0) { return (uint32_t)gd_property_info_hint_string(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_property_info_usage(uint32_t p0) { return (uint32_t)gd_property_info_usage(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { gd_classdb_register(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_methods(uint32_t p0, uint32_t p1) { gd_classdb_register_methods(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_constant(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { gd_classdb_register_constant(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_property(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_classdb_register_property(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_property_indexed(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, int32_t p4) { gd_classdb_register_property_indexed(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_property_group(uint32_t p0, uint32_t p1, uint32_t p2) { gd_classdb_register_property_group(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_property_sub_group(uint32_t p0, uint32_t p1, uint32_t p2) { gd_classdb_register_property_sub_group(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_signal(uint32_t p0, uint32_t p1, uint32_t p2) { gd_classdb_register_signal(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_register_removal(uint32_t p0) { gd_classdb_register_removal(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_WorkerThreadPool_add_task(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_classdb_WorkerThreadPool_add_task(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_classdb_WorkerThreadPool_add_group_task(uint32_t p0, uint32_t p1, int32_t p2, int32_t p3, uint32_t p4, uint32_t p5) { gd_classdb_WorkerThreadPool_add_group_task(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_classdb_XMLParser_load(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_classdb_XMLParser_load(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_dictionary_access(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { gd_packed_dictionary_access(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_dictionary_modify(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12) { gd_packed_dictionary_modify(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_editor_add_documentation(uint32_t p0, int32_t p1) { gd_editor_add_documentation(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_editor_add_plugin(uint32_t p0) { gd_editor_add_plugin(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_editor_end_plugin(uint32_t p0) { gd_editor_end_plugin(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_iterator_make(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { gd_iterator_make(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_iterator_next(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { return gd_iterator_next(p0, p1, p2, p3, p4, p5, p6, p7) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_iterator_load(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12, uint32_t p13) { gd_iterator_load(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_library_location(void) { return (uint32_t)gd_library_location(); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_log_error(uint32_t p0, int32_t p1, uint32_t p2, int32_t p3, uint32_t p4, int32_t p5, uint32_t p6, int32_t p7, int32_t p8, uint32_t p9) { gd_log_error(wasm_gd_string_arg(p0, p1), p1, wasm_gd_string_arg(p2, p3), p3, wasm_gd_string_arg(p4, p5), p5, wasm_gd_string_arg(p6, p7), p7, p8, p9); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_log_warning(uint32_t p0, int32_t p1, uint32_t p2, int32_t p3, uint32_t p4, int32_t p5, uint32_t p6, int32_t p7, int32_t p8, uint32_t p9) { gd_log_warning(wasm_gd_string_arg(p0, p1), p1, wasm_gd_string_arg(p2, p3), p3, wasm_gd_string_arg(p4, p5), p5, wasm_gd_string_arg(p6, p7), p7, p8, p9); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_memory_sizeof(uint32_t p0) { return (int32_t)gd_memory_sizeof(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_make(uint32_t p0) { return (uint32_t)gd_object_make(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_call(uint32_t p0, uint32_t p1, uint32_t p2, int32_t p3, uint32_t p4, uint32_t p5) { gd_object_call(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_name(uint32_t p0) { return (uint32_t)gd_object_name(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_type(uint32_t p0) { return (uint32_t)gd_object_type(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_cast(uint32_t p0, uint32_t p1) { return (uint32_t)gd_object_cast(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_lookup(uint32_t p0, uint32_t p1) { return (uint32_t)gd_object_lookup(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_global(uint32_t p0) { return (uint32_t)gd_object_global(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_extension_setup(uint32_t p0, uint32_t p1, uint32_t p2) { gd_object_extension_setup(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_extension_fetch(uint32_t p0) { return (uint32_t)gd_object_extension_fetch(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_extension_close(uint32_t p0) { gd_object_extension_close(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_id(uint32_t p0, uint32_t p1) { gd_object_id(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_id_inside_variant(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { gd_object_id_inside_variant(p0, p1, p2, p3, p4, p5, p6); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_method_lookup(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { return (uint32_t)gd_object_method_lookup(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_script_make(uint32_t p0) { return (uint32_t)gd_object_script_make(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_script_call(uint32_t p0, uint32_t p1, uint32_t p2, int32_t p3, uint32_t p4, uint32_t p5) { gd_object_script_call(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_script_setup(uint32_t p0, uint32_t p1) { gd_object_script_setup(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_script_fetch(uint32_t p0, uint32_t p1) { return (uint32_t)gd_object_script_fetch(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_script_defines_method(uint32_t p0, uint32_t p1) { return gd_object_script_defines_method(p0, p1) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_script_property_state_add(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8) { gd_object_script_property_state_add(p0, p1, p2, p3, p4, p5, p6, p7, p8); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_object_script_placeholder_create(uint32_t p0, uint32_t p1, uint32_t p2) { return (uint32_t)gd_object_script_placeholder_create(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_script_placeholder_update(uint32_t p0, uint32_t p1, uint32_t p2) { gd_object_script_placeholder_update(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_object_unsafe_free(uint32_t p0) { gd_object_unsafe_free(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_byte_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_byte_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_byte_array_access(uint32_t p0, uint32_t p1, int32_t p2) { return (uint32_t)gd_packed_byte_array_access(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_color_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_color_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_color_array_access(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3) { gd_packed_color_array_access(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_float32_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_float32_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE float wasm_gd_packed_float32_array_access(uint32_t p0, uint32_t p1, int32_t p2) { return (float)gd_packed_float32_array_access(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_float64_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_float64_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE double wasm_gd_packed_float64_array_access(uint32_t p0, uint32_t p1, int32_t p2) { return (double)gd_packed_float64_array_access(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_int32_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_int32_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_packed_int32_array_access(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_packed_int32_array_access(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_int64_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_int64_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_int64_array_access(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3) { gd_packed_int64_array_access(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_string_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_string_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_string_array_access(uint32_t p0, uint32_t p1, int32_t p2) { return (uint32_t)gd_packed_string_array_access(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_vector2_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_vector2_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_vector2_array_access(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3) { gd_packed_vector2_array_access(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_vector3_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_vector3_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_vector3_array_access(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3) { gd_packed_vector3_array_access(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_packed_vector4_array_unsafe(uint32_t p0, uint32_t p1) { return (uint32_t)gd_packed_vector4_array_unsafe(p0, p1); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_packed_vector4_array_access(uint32_t p0, uint32_t p1, int32_t p2, uint32_t p3) { gd_packed_vector4_array_access(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_ref_get_object(uint32_t p0) { return (uint32_t)gd_ref_get_object(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_ref_set_object(uint32_t p0, uint32_t p1) { gd_ref_set_object(p0, p1); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_access(uint32_t p0, int32_t p1) { return (int32_t)gd_string_access(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_resize(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_resize(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_unsafe(uint32_t p0) { return (uint32_t)gd_string_unsafe(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_append(uint32_t p0, uint32_t p1) { return (uint32_t)gd_string_append(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_append_rune(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_append_rune(p0, p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_decode_latin1(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_decode_latin1(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_decode_utf8(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_decode_utf8(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_decode_utf16(uint32_t p0, int32_t p1, uint32_t p2) { return (uint32_t)gd_string_decode_utf16(wasm_gd_string_arg(p0, p1), p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_decode_utf32(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_decode_utf32(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_decode_wide(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_decode_wide(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_encode_latin1(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_string_encode_latin1(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_encode_utf8(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_string_encode_utf8(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_encode_utf16(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_string_encode_utf16(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_encode_utf32(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_string_encode_utf32(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE int32_t wasm_gd_string_encode_wide(uint32_t p0, uint32_t p1, int32_t p2) { return (int32_t)gd_string_encode_wide(p0, p1, p2); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_intern_latin1(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_intern_latin1(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_string_intern_utf8(uint32_t p0, int32_t p1) { return (uint32_t)gd_string_intern_utf8(wasm_gd_string_arg(p0, p1), p1); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_thread_is_main(void) { return gd_thread_is_main() ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_zero(uint32_t p0) { gd_variant_zero(p0); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_copy(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { gd_variant_copy(p0, p1, p2, p3, p4, p5, p6); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_call(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, int32_t p8, uint32_t p9, uint32_t p10) { gd_variant_call(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_eval(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12, uint32_t p13) { return gd_variant_eval(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_hash(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { gd_variant_hash(p0, p1, p2, p3, p4, p5, p6); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_bool(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { return gd_variant_bool(p0, p1, p2, p3, p4, p5) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_text(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { return (uint32_t)gd_variant_text(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_type(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { return (uint32_t)gd_variant_type(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_deep_copy(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { gd_variant_deep_copy(p0, p1, p2, p3, p4, p5, p6); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_deep_hash(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, int32_t p6, uint32_t p7) { gd_variant_deep_hash(p0, p1, p2, p3, p4, p5, p6, p7); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_get_index(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12) { return gd_variant_get_index(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_get_array(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, int32_t p6, uint32_t p7, uint32_t p8) { return gd_variant_get_array(p0, p1, p2, p3, p4, p5, p6, p7, p8) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_get_field(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7) { return gd_variant_get_field(p0, p1, p2, p3, p4, p5, p6, p7) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_has_index(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11) { return gd_variant_has_index(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_has_method(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { return gd_variant_has_method(p0, p1, p2, p3, p4, p5, p6) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_set_index(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12, uint32_t p13, uint32_t p14, uint32_t p15, uint32_t p16, uint32_t p17) { return gd_variant_set_index(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_set_array(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, int32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12, uint32_t p13) { return gd_variant_set_array(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_set_field(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9, uint32_t p10, uint32_t p11, uint32_t p12) { return gd_variant_set_field(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) ? 1u : 0u; }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_call(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_call(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_eval(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_eval(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_free(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { gd_variant_unsafe_free(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_make_native(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7, uint32_t p8, uint32_t p9) { gd_variant_unsafe_make_native(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_from_native(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_from_native(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_variant_unsafe_internal_pointer(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6) { return (uint32_t)gd_variant_unsafe_internal_pointer(p0, p1, p2, p3, p4, p5, p6); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_get_field(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_get_field(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_get_array(uint32_t p0, int32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5) { gd_variant_unsafe_get_array(p0, p1, p2, p3, p4, p5); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_get_index(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_get_index(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_set_field(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_variant_unsafe_set_field(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_set_array(uint32_t p0, int32_t p1, uint32_t p2, uint32_t p3, uint32_t p4) { gd_variant_unsafe_set_array(p0, p1, p2, p3, p4); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_variant_unsafe_set_index(uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3) { gd_variant_unsafe_set_index(p0, p1, p2, p3); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_major(void) { return (uint32_t)gd_version_major(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_minor(void) { return (uint32_t)gd_version_minor(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_patch(void) { return (uint32_t)gd_version_patch(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_hex(void) { return (uint32_t)gd_version_hex(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_status(void) { return (uint32_t)gd_version_status(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_build(void) { return (uint32_t)gd_version_build(); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_hash(void) { return (uint32_t)gd_version_hash(); }
EMSCRIPTEN_KEEPALIVE void wasm_gd_version_timestamp(uint32_t p0) { gd_version_timestamp(p0); }
EMSCRIPTEN_KEEPALIVE uint32_t wasm_gd_version_string(void) { return (uint32_t)gd_version_string(); }
}
