package main

import (
	"fmt"
	"io"
	"os"
	"reflect"
	"strings"

	"graphics.gd/internal/gdextension"
	"graphics.gd/variant/Color"
	"graphics.gd/variant/Vector2"
	"graphics.gd/variant/Vector3"
	"graphics.gd/variant/Vector4"
	"runtime.link/api"
)

func generate_gdextension_web_cgo_callbacks() error {
	file, err := os.Create("./internal/gdextension_web_cgo_callbacks.cpp")
	if err != nil {
		return err
	}
	defer file.Close()
	// The same trampolines are included by gd.h when it is compiled for the
	// web (see the __EMSCRIPTEN__ branch there); relink.sh copies this
	// header next to gd.h in the engine tree.
	root, err := os.Create("../gd_web_callbacks.h")
	if err != nil {
		return err
	}
	defer root.Close()
	h := io.MultiWriter(file, root)

	fmt.Fprint(h, "// Code generated by ./internal/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(h, "#include <stdlib.h>\n#include <stdbool.h>\n#include <emscripten/emscripten.h>\n\n")

	for fn := range api.StructureOf(&gdextension.On).Iter() {
		name := fn.Tags.Get("gd")
		if name == "on_init" {
			continue
		}
		returns := getReturn(fn.Type)
		if returns != nil {
			if returns == reflect.TypeFor[int]() {
				returns = reflect.TypeFor[int32]()
			}
		}

		// EM_JS return type
		var retType string
		if returns != nil {
			if ctype := ctypeOf(returns); ctype != "" {
				retType = ctype
			} else {
				return fmt.Errorf("unsupported return type %s for function %s", returns, name)
			}
		} else {
			retType = "void"
		}

		// EM_JS(return_type, gd_name, (params), { body });
		fmt.Fprintf(h, "EM_JS(%s, gd_%s, (", retType, name)
		for i, arg := range args_flat(fn.Type, true) {
			if i > 0 {
				fmt.Fprint(h, ", ")
			}
			if ctype := ctypeOf(arg); ctype != "" {
				if ctype == "int64_t" {
					ctype = "int32_t"
				}
				fmt.Fprintf(h, "%s p%d", ctype, i)
			} else {
				panic(fmt.Sprintf("unsupported type %s for parameter %d in function %s", arg, i, fn.Tags.Get("gd")))
			}
		}
		fmt.Fprint(h, "), {\n\t")

		if returns != nil {
			fmt.Fprint(h, "return ")
		}
		fmt.Fprintf(h, "GD.%s(", name)
		for i := range args_flat(fn.Type, true) {
			if i > 0 {
				fmt.Fprint(h, ", ")
			}
			fmt.Fprintf(h, "p%d", i)
		}
		fmt.Fprint(h, ");\n")
		fmt.Fprint(h, "});\n")
	}

	return nil
}

// The hot-path functions below have hand-written direct bindings in
// startup_wasm_web.go (Go) and gd.c (engine wrappers with custom bodies),
// so the uniform generators skip them.
var handWrittenWebImports = map[string]bool{
	"memory_malloc": true, "memory_resize": true, "memory_clear": true,
	"memory_free": true, "memory_load_byte": true, "memory_load_u16": true,
	"memory_load_u32": true, "memory_edit_byte": true, "memory_edit_u16": true,
	"memory_edit_u32": true, "memory_edit_u64": true, "memory_edit_128": true,
	"memory_edit_256": true, "memory_edit_512": true, "object_unsafe_call": true,
}

// wasmWebTypeOf maps a flattened (args_flat x32) argument type to the Go type
// used in a //go:wasmimport declaration for the web (js/wasm) target.
func wasmWebTypeOf(rtype reflect.Type) string {
	switch rtype.Kind() {
	case reflect.String, reflect.Slice:
		return "uint32" // engine-memory address (length follows as its own arg)
	case reflect.Int, reflect.Int32:
		return "int32"
	case reflect.Bool:
		return "uint32"
	case reflect.Float32:
		return "float32"
	case reflect.Float64:
		return "float64"
	default:
		return "uint32"
	}
}

// cWebTypeOf is the C equivalent of wasmWebTypeOf.
func cWebTypeOf(rtype reflect.Type) string {
	switch rtype.Kind() {
	case reflect.Int, reflect.Int32:
		return "int32_t"
	case reflect.Float32:
		return "float"
	case reflect.Float64:
		return "double"
	default:
		return "uint32_t"
	}
}

// toWasmWebValue converts a Go-side value to the flattened wasmimport
// argument(s): 64-bit scalars split into (hi, lo) uint32 pairs to match the
// UINT64()/INT64() parameter macros in gd.c's emscripten branch.
func toWasmWebValue(value string, rtype reflect.Type) string {
	switch rtype.Kind() {
	case reflect.Uint64:
		return fmt.Sprintf("uint32(uint64(%s)>>32), uint32(uint64(%[1]s))", value)
	case reflect.Int64:
		return fmt.Sprintf("uint32(uint64(%s)>>32), uint32(uint64(%[1]s))", value)
	case reflect.Bool:
		return fmt.Sprintf("web_gd_bool(%s)", value)
	case reflect.Int, reflect.Int32:
		return fmt.Sprintf("int32(%s)", value)
	case reflect.Float32:
		return fmt.Sprintf("float32(%s)", value)
	case reflect.Float64:
		return fmt.Sprintf("float64(%s)", value)
	default:
		return fmt.Sprintf("uint32(%s)", value)
	}
}

// generate_startup_wasm_v2 emits direct //go:wasmimport bindings for the
// whole gdextension.Host surface on the web target, replacing the
// syscall/js round trips of startup_js_v2.go (whose init runs first and is
// then overridden here; hand-written hot paths in startup_wasm_web.go still
// override both). The engine-side counterparts live in the generated
// gd_web_exports.h.
func generate_startup_wasm_v2() error {
	f, err := os.Create("startup_wasm_v2.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, "// Code generated by ./internal/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(f, "//go:build js\n\n")
	fmt.Fprint(f, "package startup\n\n")
	fmt.Fprint(f, "import \"graphics.gd/internal/gdextension\"\n")
	fmt.Fprint(f, "import \"graphics.gd/internal/gdmemory\"\n\n")
	fmt.Fprint(f, "func web_gd_bool(b bool) uint32 {\n\tif b {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\n")

	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		if name == "" || handWrittenWebImports[name] {
			continue
		}
		fmt.Fprintf(f, "//go:wasmimport gd %s\n", name)
		fmt.Fprintf(f, "func web_gd_%s(", name)
		for i, arg := range args_flat(fn.Type, true) {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			fmt.Fprintf(f, "p%d %s", i, wasmWebTypeOf(arg))
		}
		fmt.Fprint(f, ")")
		if returns := getReturn(fn.Type); returns != nil {
			fmt.Fprintf(f, " %s", wasmWebTypeOf(flatReturn(returns)))
		}
		fmt.Fprintln(f)
	}
	fmt.Fprintln(f)

	fmt.Fprintln(f, "func init() {")
	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		if name == "" || handWrittenWebImports[name] {
			continue
		}
		fmt.Fprintf(f, "\tgdextension.Host.%s = func", strings.Join(append(fn.Path, fn.Name), "."))
		writeGoFunctionArguments(f, fn, false, goTypeOf)
		writeGoFunctionResults(f, fn, false, goTypeOf)
		fmt.Fprintf(f, " {\n")
		prepareArguments(f, fn, true)
		for i := range fn.NumIn() {
			if fn.Type.In(i).Kind() == reflect.String {
				fmt.Fprintf(f, "\t\tstr%d := gdmemory.CopyBufferToEngine([]byte(p%[1]d))\n", i)
			}
		}
		if result := getReturn(fn.Type); result != nil {
			switch result.Kind() {
			case reflect.Array:
				fmt.Fprintf(f, "\t\tresult = %s{%s(", goTypeOf(result), goTypeOf(result.Elem()))
			case reflect.Bool:
				fmt.Fprintf(f, "\t\tresult = %s(0 != ", goTypeOf(result))
			default:
				fmt.Fprintf(f, "\t\tresult = %s(", goTypeOf(result))
			}
		} else {
			fmt.Fprint(f, "\t\t")
		}
		fmt.Fprintf(f, "web_gd_%s(", name)
		for i := range fn.NumIn() {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			arg := fn.Type.In(i)
			switch arg.Kind() {
			case reflect.Array:
				if strings.HasPrefix(arg.Name(), "PackedArray[") {
					fmt.Fprintf(f, "pak%d[0], pak%[1]d[1]", i)
				} else {
					for j := range arg.Len() {
						if j > 0 {
							fmt.Fprint(f, ", ")
						}
						fmt.Fprint(f, toWasmWebValue(fmt.Sprintf("p%d[%d]", i, j), arg.Elem()))
					}
				}
			case reflect.String:
				fmt.Fprintf(f, "uint32(str%d), int32(len(p%[1]d))", i)
			case reflect.Slice:
				fmt.Fprintf(f, "uint32(buf%d), int32(len(p%d))", i, i)
			case reflect.UnsafePointer:
				fmt.Fprintf(f, "uint32(mem%d)", i)
			default:
				fmt.Fprint(f, toWasmWebValue(argName(arg, i), arg))
			}
		}
		fmt.Fprint(f, ")")
		if result := getReturn(fn.Type); result != nil {
			switch result.Kind() {
			case reflect.Array:
				fmt.Fprint(f, ")}")
			default:
				fmt.Fprint(f, ")")
			}
		}
		fmt.Fprintln(f)
		for i := range fn.NumIn() {
			if fn.Type.In(i).Kind() == reflect.String {
				fmt.Fprintf(f, "\t\tgdextension.Host.Memory.Free(gdextension.Pointer(str%d))\n", i)
			}
		}
		prepareResults(f, fn)
		fmt.Fprintf(f, "\t\treturn\n")
		fmt.Fprintf(f, "\t}\n")
	}
	fmt.Fprintln(f, "}")
	return nil
}

// flatReturn unwraps single-element array returns to their element type.
func flatReturn(rtype reflect.Type) reflect.Type {
	if rtype.Kind() == reflect.Array && rtype.Len() == 1 {
		return flatReturn(rtype.Elem())
	}
	return rtype
}

// generate_gd_web_exports emits the engine-side raw wasm exports
// (EMSCRIPTEN_KEEPALIVE wasm_gd_* forwarders around the gd_* functions) that
// the //go:wasmimport declarations from generate_startup_wasm_v2 bind to.
// relink.sh copies the header next to gd.cpp in the engine tree; gd.c
// includes it in its __EMSCRIPTEN__ section.
func generate_gd_web_exports() error {
	f, err := os.Create("../gd_web_exports.h")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, "// Code generated by ./startup/internal/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(f, "// Raw wasm exports so the Go module's //go:wasmimport bindings resolve\n")
	fmt.Fprint(f, "// without a JS trampoline. 64-bit values arrive as (hi, lo) uint32 pairs\n")
	fmt.Fprint(f, "// matching the UINT64()/INT64() macros; strings as (address, length) into\n")
	fmt.Fprint(f, "// engine memory.\n")
	fmt.Fprint(f, "#include <string>\n\n")
	fmt.Fprint(f, "static std::string wasm_gd_string_arg(uint32_t addr, uint32_t len) {\n")
	fmt.Fprint(f, "    return len ? std::string((const char *)(uintptr_t)addr, (size_t)len) : std::string();\n")
	fmt.Fprint(f, "}\n\n")
	fmt.Fprint(f, "extern \"C\" {\n")

	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		if name == "" || handWrittenWebImports[name] {
			continue
		}
		returns := getReturn(fn.Type)
		ret := "void"
		if returns != nil {
			ret = cWebTypeOf(flatReturn(returns))
		}
		fmt.Fprintf(f, "EMSCRIPTEN_KEEPALIVE %s wasm_gd_%s(", ret, name)
		count := 0
		for i, arg := range args_flat(fn.Type, true) {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			fmt.Fprintf(f, "%s p%d", cWebTypeOf(arg), i)
			count++
		}
		if count == 0 {
			fmt.Fprint(f, "void")
		}
		fmt.Fprint(f, ") { ")
		if returns != nil {
			if returns.Kind() == reflect.Bool || flatReturn(returns).Kind() == reflect.Bool {
				fmt.Fprintf(f, "return gd_%s(", name)
			} else {
				fmt.Fprintf(f, "return (%s)gd_%s(", ret, name)
			}
		} else {
			fmt.Fprintf(f, "gd_%s(", name)
		}
		n := 0
		forward := func(arg reflect.Type) {
			switch arg.Kind() {
			case reflect.String:
				// The gd_* convention pairs every STRING with an INT length.
				fmt.Fprintf(f, "wasm_gd_string_arg(p%d, p%d), p%d", n, n+1, n+1)
				n += 2
			case reflect.Slice, reflect.Uint64, reflect.Int64:
				fmt.Fprintf(f, "p%d, p%d", n, n+1)
				n += 2
			default:
				fmt.Fprintf(f, "p%d", n)
				n++
			}
		}
		for i := range fn.NumIn() {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			arg := fn.Type.In(i)
			if arg.Kind() == reflect.Array {
				length := arg.Len()
				if strings.HasPrefix(arg.Name(), "PackedArray[") {
					length = 1
				}
				for j := range length {
					if j > 0 {
						fmt.Fprint(f, ", ")
					}
					forward(arg.Elem())
				}
			} else {
				forward(arg)
			}
		}
		if returns != nil && (returns.Kind() == reflect.Bool || flatReturn(returns).Kind() == reflect.Bool) {
			fmt.Fprint(f, ") ? 1u : 0u; }\n")
		} else {
			fmt.Fprint(f, "); }\n")
		}
	}
	fmt.Fprint(f, "}\n")
	return nil
}

func generate_startup_js() error {
	f, err := os.Create("startup_js_v2.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, "// Code generated by ./internal/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(f, "//go:build js\n\n")
	fmt.Fprint(f, "package startup\n\n")
	fmt.Fprint(f, "import \"graphics.gd/internal/gdextension\"\n\n")
	fmt.Fprintln(f, `import "graphics.gd/internal/gdmemory"`)
	fmt.Fprint(f, "import \"syscall/js\"\n\n")
	fmt.Fprint(f, "import \"unsafe\"\n")
	fmt.Fprint(f, "import \"sync\"\n\n")

	fmt.Fprint(f, "func init() {\n")

	fmt.Fprint(f, "js.Global().Set(\"ON\", js.Global().Get(\"Object\").New())\n")

	fmt.Fprint(f, "var (\n")
	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		fmt.Fprintf(f, "gd_%s js.Value\n", name)
	}
	fmt.Fprint(f, ")\nsetup := sync.OnceFunc(func() {\n")
	fmt.Fprintln(f, `GD := js.Global().Get("GD")`)
	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		fmt.Fprintf(f, `gd_%s = GD.Get("%[1]s")`, name)
		fmt.Fprintln(f)
	}
	fmt.Fprint(f, "})\n")

	for fn := range api.StructureOf(&gdextension.Host).Iter() {
		name := fn.Tags.Get("gd")
		if name == "" {
			continue
		}
		fmt.Fprintf(f, "\tgdextension.Host.%s = func", strings.Join(append(fn.Path, fn.Name), "."))
		writeGoFunctionArguments(f, fn, false, goTypeOf)
		if fn.NumOut() > 0 {
			fmt.Fprintf(f, " (")
		}
		for i := 0; i < fn.NumOut(); i++ {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			result := fn.Type.Out(i)
			if result.Size() > 0 {
				fmt.Fprintf(f, "result %s", goTypeOf(result))
			} else {
				fmt.Fprintf(f, "_ %s", goTypeOf(result))
			}
		}
		if fn.NumOut() > 0 {
			fmt.Fprintf(f, " )")
		}
		fmt.Fprintf(f, " {\nsetup()\n")
		prepareArguments(f, fn, true)
		if result := getReturn(fn.Type); result != nil {
			switch result.Kind() {
			case reflect.Array:
				fmt.Fprintf(f, "\t\tresult = %s{%s(", goTypeOf(result), goTypeOf(result.Elem()))
			default:
				fmt.Fprintf(f, "\t\tresult = %s(", goTypeOf(result))
			}
		}
		fmt.Fprintf(f, "gd_%s.Invoke(", name)
		for i := range fn.NumIn() {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			arg := fn.Type.In(i)
			switch arg.Kind() {
			case reflect.Array:
				var length = arg.Len()
				if strings.HasPrefix(arg.Name(), "PackedArray[") {
					fmt.Fprintf(f, "pak%d[0], pak%[1]d[1]", i)
				} else {
					for j := range length {
						if j > 0 {
							fmt.Fprint(f, ", ")
						}
						fmt.Fprint(f, toJSValue(fmt.Sprintf("p%d[%d]", i, j), arg.Elem()))
					}
				}
			case reflect.String:
				fmt.Fprintf(f, "string(p%d), len(p%[1]d)", i)
			case reflect.Slice:
				fmt.Fprintf(f, "uint32(buf%d), len(p%d)", i, i)
			case reflect.UnsafePointer:
				fmt.Fprintf(f, "uint32(mem%d)", i)
			default:
				fmt.Fprint(f, toJSValue(argName(arg, i), arg))
			}
		}
		if result := getReturn(fn.Type); result != nil {

			switch result.Kind() {
			case reflect.Uint8, reflect.Uintptr, reflect.Int32, reflect.Uint32, reflect.UnsafePointer, reflect.Uint16, reflect.Int:
				fmt.Fprintf(f, ").Int())")
			case reflect.Float32, reflect.Float64:
				fmt.Fprintf(f, ").Float())")
			case reflect.Bool:
				fmt.Fprintf(f, ").Bool())")
			case reflect.Int64:
				fmt.Fprintf(f, ").Float())))")
			case reflect.Uint64:
				fmt.Fprintf(f, ").Float()))")
			case reflect.Array:
				fmt.Fprintf(f, ")")
				switch result.Elem().Kind() {
				case reflect.Uint8, reflect.Uintptr, reflect.Int32, reflect.Uint32, reflect.UnsafePointer, reflect.Uint16, reflect.Int:
					fmt.Fprintf(f, ".Int()")
				case reflect.Float32, reflect.Float64:
					fmt.Fprintf(f, ".Float()")
				case reflect.Bool:
					fmt.Fprintf(f, ".Bool()")
				}
				fmt.Fprintf(f, ")}")

			default:
				fmt.Fprintf(f, "))")
			}
		} else {
			fmt.Fprint(f, ")")
		}
		fmt.Fprintln(f)
		prepareResults(f, fn)
		fmt.Fprintf(f, "\t\treturn\n")
		fmt.Fprintf(f, "\t}\n")
	}
	fmt.Fprint(f, "}\n")

	return nil
}

func prepareArguments(f io.Writer, fn api.Function, js bool) {
	for i := range fn.NumIn() {
		arg := fn.Type.In(i)
		if arg.Kind() == reflect.Slice {
			fmt.Fprintf(f, "\t\tbuf%d := gdmemory.CopyBufferToEngine(p%[1]d)\n", i)
		}
		if js {
			if strings.HasPrefix(arg.Name(), "PackedArray[") {
				fmt.Fprintf(f, "\t\tpak%d := p%[1]d.JS()\n", i)
			}
		}
		if arg.Kind() == reflect.UnsafePointer {
			switch arg {
			case reflect.TypeFor[gdextension.CallAccepts[any]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.CopyArguments(shape, p%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[any]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(shape)\n", i)
			case reflect.TypeFor[gdextension.CallAccepts[gdextension.Variant]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.CopyVariants(p%[1]d, p%d)\n", i, i-1)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.Variant]](), reflect.TypeFor[gdextension.CallReturns[gdextension.Iterator]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeVariant)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.CallError]](), reflect.TypeFor[gdextension.CallReturns[Vector3.XYZ]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeVariant)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Vector2.XY]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeVector2)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.Callable]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeCallable)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Color.RGBA]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeColor)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Vector4.XYZW]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeVector4)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[uint64]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeRID)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[int64]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeInt)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.ObjectID]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.MakeResult(gdextension.SizeInt)\n", i)
			case reflect.TypeFor[gdextension.CallMutates[any]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.CopyReceiver(shape, p%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallMutates[gdextension.Iterator]]():
				fmt.Fprintf(f, "\t\tmem%d := gdmemory.CopyReceiver(gdextension.SizeVariant, p%[1]d)\n", i)
			}
		}
	}
}

func prepareResults(f io.Writer, fn api.Function) {
	for i := range fn.NumIn() {
		arg := fn.Type.In(i)
		if arg.Kind() == reflect.Slice {
			fmt.Fprintf(f, "\t\tgdmemory.CopyBufferToGo(buf%[1]d, p%[1]d)\n", i)
		}
		if arg.Kind() == reflect.UnsafePointer {
			switch arg {
			case reflect.TypeFor[gdextension.CallReturns[any]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(shape, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.Variant]](), reflect.TypeFor[gdextension.CallReturns[gdextension.Iterator]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeVariant, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.CallError]](), reflect.TypeFor[gdextension.CallReturns[Vector3.XYZ]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeVector3, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Vector2.XY]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeVector2, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.Callable]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeCallable, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Color.RGBA]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeColor, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[Vector4.XYZW]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeVector4, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallMutates[any]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(shape>>4, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallMutates[gdextension.Iterator]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeVariant, p%d, mem%[1]d)\n", i)
			case reflect.TypeFor[gdextension.CallReturns[gdextension.ObjectID]](), reflect.TypeFor[gdextension.CallReturns[uint64]](), reflect.TypeFor[gdextension.CallReturns[int64]]():
				fmt.Fprintf(f, "\t\tgdmemory.LoadResult(gdextension.SizeInt, p%d, mem%[1]d)\n", i)
			}
		}
	}
}

func jsTypeOf(rtype reflect.Type) string {
	switch rtype.Kind() {
	case reflect.Uintptr:
		return "uint32"
	default:
		return goTypeOf(rtype)
	}
}

func fromJS(rtype reflect.Type, value string) string {
	switch rtype.Kind() {
	case reflect.Uint8, reflect.Uintptr, reflect.Int32, reflect.Uint32, reflect.UnsafePointer, reflect.Int:
		return fmt.Sprintf("%s.Int()", value)
	case reflect.Bool:
		return fmt.Sprintf("%s.Bool()", value)
	case reflect.Uint64:
		return fmt.Sprintf("%s.Int()", value)
	case reflect.Int64:
		return fmt.Sprintf("gdmemory.Int64frombits(math.Float64bits(%s.Float()))", value)
	default:
		return value
	}
}

func wasmTypeOf(rtype reflect.Type) string {
	switch rtype.Kind() {
	case reflect.Int32:
		return "int32"
	case reflect.Int:
		return "int32"
	default:
		return "uint32"
	}
}

func wasmReturnTypeOf(rtype reflect.Type) string {
	if rtype.Kind() == reflect.Array && rtype.Len() == 1 {
		return wasmReturnTypeOf(rtype.Elem())
	}
	return wasmTypeOf(rtype)
}

func generate_startup_wasm_exports() error {
	f, err := os.Create("startup_wasm_exports.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, "// Code generated by ./internal/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(f, "//go:build js\n\n")
	fmt.Fprint(f, "package startup\n\n")
	fmt.Fprint(f, "import \"graphics.gd/internal/gdextension\"\n")
	fmt.Fprint(f, "import \"graphics.gd/internal/threadcheck\"\n\n")

	for fn := range api.StructureOf(&gdextension.On).Iter() {
		name := fn.Tags.Get("gd")
		returns := getReturn(fn.Type)
		if returns != nil && returns.Kind() == reflect.Int {
			returns = reflect.TypeFor[int32]()
		}

		// //go:wasmexport gd_<name>
		fmt.Fprintf(f, "//go:wasmexport gd_%s\nfunc gd_%[1]s(", name)
		for i, arg := range args_flat(fn.Type, true) {
			if i > 0 {
				fmt.Fprint(f, ", ")
			}
			fmt.Fprintf(f, "p%d %s", i, wasmTypeOf(arg))
		}
		fmt.Fprint(f, ")")
		if returns != nil {
			fmt.Fprintf(f, " %s", wasmReturnTypeOf(returns))
		}
		fmt.Fprint(f, " {\n")
		// The calling goroutine drives this engine callback, so its wrappers
		// are frame-temporaries for the duration (see threadcheck.EnterFrame).
		fmt.Fprint(f, "\tdefer threadcheck.LeaveFrame(threadcheck.EnterFrame())\n")

		// Function body
		if returns == nil {
			fmt.Fprint(f, "\t")
		} else if returns.Kind() == reflect.Bool {
			if fn.NumOut() > 1 {
				fmt.Fprint(f, "\t")
				for i := 0; i < fn.NumOut(); i++ {
					if i > 0 {
						fmt.Fprint(f, ", ")
					}
					if fn.Type.Out(i).Size() > 0 {
						fmt.Fprint(f, "result")
					} else {
						fmt.Fprint(f, "_")
					}
				}
				fmt.Fprint(f, " := ")
			} else {
				fmt.Fprint(f, "\tif ")
			}
		} else if fn.NumOut() > 1 {
			fmt.Fprint(f, "\t")
			for i := 0; i < fn.NumOut(); i++ {
				if i > 0 {
					fmt.Fprint(f, ", ")
				}
				if fn.Type.Out(i).Size() > 0 {
					fmt.Fprint(f, "result")
				} else {
					fmt.Fprint(f, "_")
				}
			}
			fmt.Fprint(f, " := ")
		} else {
			fmt.Fprintf(f, "\treturn %s(", wasmReturnTypeOf(returns))
		}

		// Generate the function call
		fmt.Fprintf(f, "gdextension.On.%s(", strings.Join(append(fn.Path, fn.Name), "."))
		var n int
		for i := range fn.NumIn() {
			if n > 0 {
				fmt.Fprint(f, ", ")
			}
			arg := fn.Type.In(i)
			switch arg.Kind() {
			case reflect.Array:
				length := arg.Len()
				if strings.HasPrefix(arg.Name(), "PackedArray[") {
					length = 1
				}
				fmt.Fprintf(f, "%s{", toGoValue(arg))
				for j := 0; j < length; j++ {
					if j > 0 {
						fmt.Fprint(f, ", ")
					}
					if arg.Elem().Kind() == reflect.Uint64 || arg.Elem().Kind() == reflect.Int64 {
						fmt.Fprintf(f, "%s(uint64(uint64(p%d)<<32)|uint64(p%d))", toGoValue(arg.Elem()), n, n+1)
						n += 2
					} else {
						fmt.Fprintf(f, "%s(p%d)", toGoValue(arg.Elem()), n)
						n++
					}
				}
				fmt.Fprint(f, "}")
			case reflect.Bool:
				fmt.Fprintf(f, "p%d != 0", n)
				n++
			default:
				fmt.Fprintf(f, "%s(p%d)", toGoValue(arg), n)
				n++
			}
		}
		fmt.Fprint(f, ")")

		// Handle return closing
		if returns == nil {
			fmt.Fprint(f, "\n")
		} else if returns.Kind() == reflect.Bool {
			if fn.NumOut() > 1 {
				fmt.Fprint(f, "\n\tif result {\n\t\treturn 1\n\t}\n\treturn 0\n")
			} else {
				fmt.Fprint(f, " {\n\t\treturn 1\n\t}\n\treturn 0\n")
			}
		} else if fn.NumOut() > 1 {
			fmt.Fprint(f, "\n")
			if returns.Kind() == reflect.Array && returns.Len() == 1 {
				fmt.Fprintf(f, "\treturn %s(result[0])\n", wasmReturnTypeOf(returns))
			} else {
				fmt.Fprintf(f, "\treturn %s(result)\n", wasmReturnTypeOf(returns))
			}
		} else {
			if returns.Kind() == reflect.Array && returns.Len() == 1 {
				fmt.Fprint(f, "[0])\n")
			} else {
				fmt.Fprint(f, ")\n")
			}
		}

		fmt.Fprint(f, "}\n\n")
	}

	return nil
}

func toJSValue(value string, rtype reflect.Type) string {
	if strings.HasPrefix(rtype.Name(), "PackedArray[") {
		return toJSValue(value, reflect.TypeFor[[1]uint64]())
	}
	if rtype == reflect.TypeFor[gdextension.Pointer]() {
		return toJSValue(value, reflect.TypeFor[uint32]())
	}
	switch rtype.Kind() {
	case reflect.Int32, reflect.Uint32:
		return fmt.Sprintf("%s(%s)", strings.ToLower(rtype.Kind().String()), value)
	case reflect.Uintptr, reflect.UnsafePointer:
		return fmt.Sprintf("uint32(%s)", value)
	case reflect.Uint64:
		return fmt.Sprintf("uint32(%s>>32), uint32(%[1]s & 0xFFFFFFFF)", value)
	case reflect.Int64:
		return fmt.Sprintf("uint32(*(*uint64)(unsafe.Pointer(&%s))>>32), uint32(*(*uint64)(unsafe.Pointer(&%[1]s)) & 0xFFFFFFFF)", value)
	default:
		return value
	}
}
