#!/bin/sh
# gen_helper.sh - cross-compile the borrowed-loader helper (helper_src.h) against
# an old glibc and embed the resulting ELF as C byte arrays (helper_bin_*.c).
#
# The embedded helper lets the common case -- a glibc host with no C compiler --
# work with zero runtime tooling: dlopen.c loads it from an in-memory fd (see
# embedded_helper_fd) instead of compiling helper_src.h on the fly.
#
# We build with `zig cc` because it can target a specific, ancient glibc from any
# host (including this musl dev box): glibc 2.17 (2012, RHEL7/manylinux2014) is
# old enough to run on essentially every currently-supported glibc distro, while
# the symbols still resolve forward against newer host glibc at load time.
#
# Regenerate whenever helper_src.h changes:
#   ZIG=/path/to/zig ./gen_helper.sh
# The generated helper_bin_amd64.c / helper_bin_arm64.c are committed; building
# graphics.gd itself needs no zig, only regenerating these does.
set -e
cd "$(dirname "$0")"

ZIG="${ZIG:-zig}"
command -v "$ZIG" >/dev/null 2>&1 || { echo "gen_helper.sh: need zig (set ZIG=/path/to/zig)"; exit 1; }

GLIBC=2.17
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# 1. Extract the HELPER string from helper_src.h into a standalone .c using the
#    real preprocessor, so the embedded binary and the runtime-compiled fallback
#    are byte-for-byte the same program.
cat > "$WORK/extract.c" <<'EOF'
#include <stdio.h>
#include "helper_src.h"
int main(void){ fputs(HELPER, stdout); return 0; }
EOF
cc -I. "$WORK/extract.c" -o "$WORK/extract"
"$WORK/extract" > "$WORK/helper_main.c"

emit() { # emit <arch-triple> <goarch> <out.c>
	triple="$1"; goarch="$2"; out="$3"
	echo ">> building helper for $goarch ($triple, glibc $GLIBC)"
	# -pie: the in-process loader (elf_map in dlopen.c) only handles ET_DYN.
	# -s: strip, the bytes ride in every shipped binary.
	"$ZIG" cc -target "$triple" -pie -fPIE -O2 -s \
		"$WORK/helper_main.c" -o "$WORK/helper.$goarch" -ldl -lpthread
	sz=$(wc -c < "$WORK/helper.$goarch")
	echo ">> $goarch helper is $sz bytes"
	# Arch guard so exactly one helper_bin_*.c defines the symbol per target.
	case "$goarch" in
		amd64) guard="__x86_64__" ;;
		arm64) guard="__aarch64__" ;;
	esac
	{
		printf '/* Generated by gen_helper.sh from helper_src.h -- do not edit. */\n'
		printf '/* Prebuilt borrowed-loader helper: %s, glibc %s, %s bytes. */\n' "$goarch" "$GLIBC" "$sz"
		printf '#ifndef __GLIBC__\n'
		printf '#if defined(%s)\n' "$guard"
		printf 'const unsigned char helper_bin[] = {\n'
		od -An -v -tu1 "$WORK/helper.$goarch" \
			| awk '{ for(i=1;i<=NF;i++){ printf "%s,", $i; if(++n%20==0) printf "\n" } } END{ printf "\n" }'
		printf '};\n'
		printf 'const unsigned int helper_bin_len = %s;\n' "$sz"
		printf '#endif\n'
		printf '#endif /* __GLIBC__ */\n'
	} > "$out"
	echo ">> wrote $out"
}

emit x86_64-linux-gnu.$GLIBC  amd64 helper_bin_amd64.c
emit aarch64-linux-gnu.$GLIBC arm64 helper_bin_arm64.c
echo ">> done"
