// Code generated by ./internal/cmd/generate; DO NOT EDIT.
//go:build js

package startup

import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdmemory"

func web_gd_bool(b bool) uint32 {
	if b {
		return 1
	}
	return 0
}

//go:wasmimport gd array_get
func web_gd_array_get(p0 uint32, p1 int32, p2 uint32)

//go:wasmimport gd array_set
func web_gd_array_set(p0 uint32, p1 int32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32)

//go:wasmimport gd builtin_name
func web_gd_builtin_name(p0 uint32, p1 uint32, p2 uint32) uint32

//go:wasmimport gd builtin_call
func web_gd_builtin_call(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_type_name
func web_gd_variant_type_name(p0 uint32) uint32

//go:wasmimport gd variant_type_make
func web_gd_variant_type_make(p0 uint32, p1 uint32, p2 int32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_type_call
func web_gd_variant_type_call(p0 uint32, p1 uint32, p2 uint32, p3 int32, p4 uint32, p5 uint32)

//go:wasmimport gd variant_type_convertable
func web_gd_variant_type_convertable(p0 uint32, p1 uint32, p2 uint32) uint32

//go:wasmimport gd variant_type_setup_array
func web_gd_variant_type_setup_array(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32)

//go:wasmimport gd variant_type_setup_dictionary
func web_gd_variant_type_setup_dictionary(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32, p13 uint32, p14 uint32, p15 uint32, p16 uint32)

//go:wasmimport gd variant_type_fetch_constant
func web_gd_variant_type_fetch_constant(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd variant_type_unsafe_constructor
func web_gd_variant_type_unsafe_constructor(p0 uint32, p1 int32) uint32

//go:wasmimport gd variant_type_evaluator
func web_gd_variant_type_evaluator(p0 uint32, p1 uint32, p2 uint32) uint32

//go:wasmimport gd variant_type_setter
func web_gd_variant_type_setter(p0 uint32, p1 uint32) uint32

//go:wasmimport gd variant_type_getter
func web_gd_variant_type_getter(p0 uint32, p1 uint32) uint32

//go:wasmimport gd variant_type_has_property
func web_gd_variant_type_has_property(p0 uint32, p1 uint32) uint32

//go:wasmimport gd variant_type_builtin_method
func web_gd_variant_type_builtin_method(p0 uint32, p1 uint32, p2 uint32, p3 uint32) uint32

//go:wasmimport gd variant_type_unsafe_call
func web_gd_variant_type_unsafe_call(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32)

//go:wasmimport gd variant_type_unsafe_make
func web_gd_variant_type_unsafe_make(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_type_unsafe_free
func web_gd_variant_type_unsafe_free(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd callable_create
func web_gd_callable_create(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd callable_lookup
func web_gd_callable_lookup(p0 uint32, p1 uint32, p2 uint32, p3 uint32) uint32

//go:wasmimport gd classdb_FileAccess_write
func web_gd_classdb_FileAccess_write(p0 uint32, p1 uint32, p2 int32)

//go:wasmimport gd classdb_FileAccess_read
func web_gd_classdb_FileAccess_read(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd classdb_Image_unsafe
func web_gd_classdb_Image_unsafe(p0 uint32) uint32

//go:wasmimport gd classdb_Image_access
func web_gd_classdb_Image_access(p0 uint32, p1 int32) uint32

//go:wasmimport gd method_list_make
func web_gd_method_list_make(p0 int32) uint32

//go:wasmimport gd method_list_push
func web_gd_method_list_push(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 int32, p7 uint32)

//go:wasmimport gd method_list_free
func web_gd_method_list_free(p0 uint32)

//go:wasmimport gd property_list_make
func web_gd_property_list_make(p0 int32) uint32

//go:wasmimport gd property_list_push
func web_gd_property_list_push(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32)

//go:wasmimport gd property_list_free
func web_gd_property_list_free(p0 uint32)

//go:wasmimport gd property_info_type
func web_gd_property_info_type(p0 uint32) uint32

//go:wasmimport gd property_info_name
func web_gd_property_info_name(p0 uint32) uint32

//go:wasmimport gd property_info_class_name
func web_gd_property_info_class_name(p0 uint32) uint32

//go:wasmimport gd property_info_hint
func web_gd_property_info_hint(p0 uint32) uint32

//go:wasmimport gd property_info_hint_string
func web_gd_property_info_hint_string(p0 uint32) uint32

//go:wasmimport gd property_info_usage
func web_gd_property_info_usage(p0 uint32) uint32

//go:wasmimport gd classdb_register
func web_gd_classdb_register(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32)

//go:wasmimport gd classdb_register_methods
func web_gd_classdb_register_methods(p0 uint32, p1 uint32)

//go:wasmimport gd classdb_register_constant
func web_gd_classdb_register_constant(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32)

//go:wasmimport gd classdb_register_property
func web_gd_classdb_register_property(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd classdb_register_property_indexed
func web_gd_classdb_register_property_indexed(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 int32)

//go:wasmimport gd classdb_register_property_group
func web_gd_classdb_register_property_group(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd classdb_register_property_sub_group
func web_gd_classdb_register_property_sub_group(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd classdb_register_signal
func web_gd_classdb_register_signal(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd classdb_register_removal
func web_gd_classdb_register_removal(p0 uint32)

//go:wasmimport gd classdb_WorkerThreadPool_add_task
func web_gd_classdb_WorkerThreadPool_add_task(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd classdb_WorkerThreadPool_add_group_task
func web_gd_classdb_WorkerThreadPool_add_group_task(p0 uint32, p1 uint32, p2 int32, p3 int32, p4 uint32, p5 uint32)

//go:wasmimport gd classdb_XMLParser_load
func web_gd_classdb_XMLParser_load(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd packed_dictionary_access
func web_gd_packed_dictionary_access(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32)

//go:wasmimport gd packed_dictionary_modify
func web_gd_packed_dictionary_modify(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32)

//go:wasmimport gd editor_add_documentation
func web_gd_editor_add_documentation(p0 uint32, p1 int32)

//go:wasmimport gd editor_add_plugin
func web_gd_editor_add_plugin(p0 uint32)

//go:wasmimport gd editor_end_plugin
func web_gd_editor_end_plugin(p0 uint32)

//go:wasmimport gd iterator_make
func web_gd_iterator_make(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32)

//go:wasmimport gd iterator_next
func web_gd_iterator_next(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32) uint32

//go:wasmimport gd iterator_load
func web_gd_iterator_load(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32, p13 uint32)

//go:wasmimport gd library_location
func web_gd_library_location() uint32

//go:wasmimport gd log_error
func web_gd_log_error(p0 uint32, p1 int32, p2 uint32, p3 int32, p4 uint32, p5 int32, p6 uint32, p7 int32, p8 int32, p9 uint32)

//go:wasmimport gd log_warning
func web_gd_log_warning(p0 uint32, p1 int32, p2 uint32, p3 int32, p4 uint32, p5 int32, p6 uint32, p7 int32, p8 int32, p9 uint32)

//go:wasmimport gd memory_sizeof
func web_gd_memory_sizeof(p0 uint32) int32

//go:wasmimport gd object_make
func web_gd_object_make(p0 uint32) uint32

//go:wasmimport gd object_call
func web_gd_object_call(p0 uint32, p1 uint32, p2 uint32, p3 int32, p4 uint32, p5 uint32)

//go:wasmimport gd object_name
func web_gd_object_name(p0 uint32) uint32

//go:wasmimport gd object_type
func web_gd_object_type(p0 uint32) uint32

//go:wasmimport gd object_cast
func web_gd_object_cast(p0 uint32, p1 uint32) uint32

//go:wasmimport gd object_lookup
func web_gd_object_lookup(p0 uint32, p1 uint32) uint32

//go:wasmimport gd object_global
func web_gd_object_global(p0 uint32) uint32

//go:wasmimport gd object_extension_setup
func web_gd_object_extension_setup(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd object_extension_fetch
func web_gd_object_extension_fetch(p0 uint32) uint32

//go:wasmimport gd object_extension_close
func web_gd_object_extension_close(p0 uint32)

//go:wasmimport gd object_id
func web_gd_object_id(p0 uint32, p1 uint32)

//go:wasmimport gd object_id_inside_variant
func web_gd_object_id_inside_variant(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32)

//go:wasmimport gd object_method_lookup
func web_gd_object_method_lookup(p0 uint32, p1 uint32, p2 uint32, p3 uint32) uint32

//go:wasmimport gd object_script_make
func web_gd_object_script_make(p0 uint32) uint32

//go:wasmimport gd object_script_call
func web_gd_object_script_call(p0 uint32, p1 uint32, p2 uint32, p3 int32, p4 uint32, p5 uint32)

//go:wasmimport gd object_script_setup
func web_gd_object_script_setup(p0 uint32, p1 uint32)

//go:wasmimport gd object_script_fetch
func web_gd_object_script_fetch(p0 uint32, p1 uint32) uint32

//go:wasmimport gd object_script_defines_method
func web_gd_object_script_defines_method(p0 uint32, p1 uint32) uint32

//go:wasmimport gd object_script_property_state_add
func web_gd_object_script_property_state_add(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32)

//go:wasmimport gd object_script_placeholder_create
func web_gd_object_script_placeholder_create(p0 uint32, p1 uint32, p2 uint32) uint32

//go:wasmimport gd object_script_placeholder_update
func web_gd_object_script_placeholder_update(p0 uint32, p1 uint32, p2 uint32)

//go:wasmimport gd object_unsafe_free
func web_gd_object_unsafe_free(p0 uint32)

//go:wasmimport gd packed_byte_array_unsafe
func web_gd_packed_byte_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_byte_array_access
func web_gd_packed_byte_array_access(p0 uint32, p1 uint32, p2 int32) uint32

//go:wasmimport gd packed_color_array_unsafe
func web_gd_packed_color_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_color_array_access
func web_gd_packed_color_array_access(p0 uint32, p1 uint32, p2 int32, p3 uint32)

//go:wasmimport gd packed_float32_array_unsafe
func web_gd_packed_float32_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_float32_array_access
func web_gd_packed_float32_array_access(p0 uint32, p1 uint32, p2 int32) float32

//go:wasmimport gd packed_float64_array_unsafe
func web_gd_packed_float64_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_float64_array_access
func web_gd_packed_float64_array_access(p0 uint32, p1 uint32, p2 int32) float64

//go:wasmimport gd packed_int32_array_unsafe
func web_gd_packed_int32_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_int32_array_access
func web_gd_packed_int32_array_access(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd packed_int64_array_unsafe
func web_gd_packed_int64_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_int64_array_access
func web_gd_packed_int64_array_access(p0 uint32, p1 uint32, p2 int32, p3 uint32)

//go:wasmimport gd packed_string_array_unsafe
func web_gd_packed_string_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_string_array_access
func web_gd_packed_string_array_access(p0 uint32, p1 uint32, p2 int32) uint32

//go:wasmimport gd packed_vector2_array_unsafe
func web_gd_packed_vector2_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_vector2_array_access
func web_gd_packed_vector2_array_access(p0 uint32, p1 uint32, p2 int32, p3 uint32)

//go:wasmimport gd packed_vector3_array_unsafe
func web_gd_packed_vector3_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_vector3_array_access
func web_gd_packed_vector3_array_access(p0 uint32, p1 uint32, p2 int32, p3 uint32)

//go:wasmimport gd packed_vector4_array_unsafe
func web_gd_packed_vector4_array_unsafe(p0 uint32, p1 uint32) uint32

//go:wasmimport gd packed_vector4_array_access
func web_gd_packed_vector4_array_access(p0 uint32, p1 uint32, p2 int32, p3 uint32)

//go:wasmimport gd ref_get_object
func web_gd_ref_get_object(p0 uint32) uint32

//go:wasmimport gd ref_set_object
func web_gd_ref_set_object(p0 uint32, p1 uint32)

//go:wasmimport gd string_access
func web_gd_string_access(p0 uint32, p1 int32) int32

//go:wasmimport gd string_resize
func web_gd_string_resize(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_unsafe
func web_gd_string_unsafe(p0 uint32) uint32

//go:wasmimport gd string_append
func web_gd_string_append(p0 uint32, p1 uint32) uint32

//go:wasmimport gd string_append_rune
func web_gd_string_append_rune(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_decode_latin1
func web_gd_string_decode_latin1(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_decode_utf8
func web_gd_string_decode_utf8(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_decode_utf16
func web_gd_string_decode_utf16(p0 uint32, p1 int32, p2 uint32) uint32

//go:wasmimport gd string_decode_utf32
func web_gd_string_decode_utf32(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_decode_wide
func web_gd_string_decode_wide(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_encode_latin1
func web_gd_string_encode_latin1(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd string_encode_utf8
func web_gd_string_encode_utf8(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd string_encode_utf16
func web_gd_string_encode_utf16(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd string_encode_utf32
func web_gd_string_encode_utf32(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd string_encode_wide
func web_gd_string_encode_wide(p0 uint32, p1 uint32, p2 int32) int32

//go:wasmimport gd string_intern_latin1
func web_gd_string_intern_latin1(p0 uint32, p1 int32) uint32

//go:wasmimport gd string_intern_utf8
func web_gd_string_intern_utf8(p0 uint32, p1 int32) uint32

//go:wasmimport gd thread_is_main
func web_gd_thread_is_main() uint32

//go:wasmimport gd variant_zero
func web_gd_variant_zero(p0 uint32)

//go:wasmimport gd variant_copy
func web_gd_variant_copy(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32)

//go:wasmimport gd variant_call
func web_gd_variant_call(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 int32, p9 uint32, p10 uint32)

//go:wasmimport gd variant_eval
func web_gd_variant_eval(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32, p13 uint32) uint32

//go:wasmimport gd variant_hash
func web_gd_variant_hash(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32)

//go:wasmimport gd variant_bool
func web_gd_variant_bool(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32) uint32

//go:wasmimport gd variant_text
func web_gd_variant_text(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32) uint32

//go:wasmimport gd variant_type
func web_gd_variant_type(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32) uint32

//go:wasmimport gd variant_deep_copy
func web_gd_variant_deep_copy(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32)

//go:wasmimport gd variant_deep_hash
func web_gd_variant_deep_hash(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 int32, p7 uint32)

//go:wasmimport gd variant_get_index
func web_gd_variant_get_index(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32) uint32

//go:wasmimport gd variant_get_array
func web_gd_variant_get_array(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 int32, p7 uint32, p8 uint32) uint32

//go:wasmimport gd variant_get_field
func web_gd_variant_get_field(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32) uint32

//go:wasmimport gd variant_has_index
func web_gd_variant_has_index(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32) uint32

//go:wasmimport gd variant_has_method
func web_gd_variant_has_method(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32) uint32

//go:wasmimport gd variant_set_index
func web_gd_variant_set_index(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32, p13 uint32, p14 uint32, p15 uint32, p16 uint32, p17 uint32) uint32

//go:wasmimport gd variant_set_array
func web_gd_variant_set_array(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 int32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32, p13 uint32) uint32

//go:wasmimport gd variant_set_field
func web_gd_variant_set_field(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32, p10 uint32, p11 uint32, p12 uint32) uint32

//go:wasmimport gd variant_unsafe_call
func web_gd_variant_unsafe_call(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_eval
func web_gd_variant_unsafe_eval(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_free
func web_gd_variant_unsafe_free(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32)

//go:wasmimport gd variant_unsafe_make_native
func web_gd_variant_unsafe_make_native(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32, p7 uint32, p8 uint32, p9 uint32)

//go:wasmimport gd variant_unsafe_from_native
func web_gd_variant_unsafe_from_native(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_internal_pointer
func web_gd_variant_unsafe_internal_pointer(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32, p5 uint32, p6 uint32) uint32

//go:wasmimport gd variant_unsafe_get_field
func web_gd_variant_unsafe_get_field(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_get_array
func web_gd_variant_unsafe_get_array(p0 uint32, p1 int32, p2 uint32, p3 uint32, p4 uint32, p5 uint32)

//go:wasmimport gd variant_unsafe_get_index
func web_gd_variant_unsafe_get_index(p0 uint32, p1 uint32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_set_field
func web_gd_variant_unsafe_set_field(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd variant_unsafe_set_array
func web_gd_variant_unsafe_set_array(p0 uint32, p1 int32, p2 uint32, p3 uint32, p4 uint32)

//go:wasmimport gd variant_unsafe_set_index
func web_gd_variant_unsafe_set_index(p0 uint32, p1 uint32, p2 uint32, p3 uint32)

//go:wasmimport gd version_major
func web_gd_version_major() uint32

//go:wasmimport gd version_minor
func web_gd_version_minor() uint32

//go:wasmimport gd version_patch
func web_gd_version_patch() uint32

//go:wasmimport gd version_hex
func web_gd_version_hex() uint32

//go:wasmimport gd version_status
func web_gd_version_status() uint32

//go:wasmimport gd version_build
func web_gd_version_build() uint32

//go:wasmimport gd version_hash
func web_gd_version_hash() uint32

//go:wasmimport gd version_timestamp
func web_gd_version_timestamp(p0 uint32)

//go:wasmimport gd version_string
func web_gd_version_string() uint32

func init() {
	gdextension.Host.Array.Get = func(p0 gdextension.Array, p1 int, p2 gdextension.CallReturns[gdextension.Variant]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_array_get(uint32(p0[0]), int32(p1), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		return
	}
	gdextension.Host.Array.Set = func(p0 gdextension.Array, p1 int, p2 gdextension.Variant) {
		web_gd_array_set(uint32(p0[0]), int32(p1), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2])))
		return
	}
	gdextension.Host.Builtin.Functions.Name = func(p0 gdextension.StringName, p1 int64) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_builtin_name(uint32(p0[0]), uint32(uint64(p1)>>32), uint32(uint64(p1))))
		return
	}
	gdextension.Host.Builtin.Functions.Call = func(p0 gdextension.FunctionID, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_builtin_call(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Builtin.Types.Name = func(p0 gdextension.VariantType) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_variant_type_name(uint32(p0)))}
		return
	}
	gdextension.Host.Builtin.Types.Make = func(p0 gdextension.VariantType, p1 gdextension.CallReturns[gdextension.Variant], p2 int, p3 gdextension.CallAccepts[gdextension.Variant], p4 gdextension.CallReturns[gdextension.CallError]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem3 := gdmemory.CopyVariants(p3, p2)
		mem4 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_type_make(uint32(p0), uint32(mem1), int32(p2), uint32(mem3), uint32(mem4))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		gdmemory.LoadResult(gdextension.SizeVector3, p4, mem4)
		return
	}
	gdextension.Host.Builtin.Types.Call = func(p0 gdextension.VariantType, p1 gdextension.StringName, p2 gdextension.CallReturns[gdextension.Variant], p3 int, p4 gdextension.CallAccepts[gdextension.Variant], p5 gdextension.CallReturns[gdextension.CallError]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem4 := gdmemory.CopyVariants(p4, p3)
		mem5 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_type_call(uint32(p0), uint32(p1[0]), uint32(mem2), int32(p3), uint32(mem4), uint32(mem5))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p5, mem5)
		return
	}
	gdextension.Host.Builtin.Types.Convertable = func(p0 gdextension.VariantType, p1 gdextension.VariantType, p2 bool) (result bool) {
		result = bool(0 != web_gd_variant_type_convertable(uint32(p0), uint32(p1), web_gd_bool(p2)))
		return
	}
	gdextension.Host.Builtin.Types.SetupArray = func(p0 gdextension.Array, p1 gdextension.VariantType, p2 gdextension.StringName, p3 gdextension.Variant) {
		web_gd_variant_type_setup_array(uint32(p0[0]), uint32(p1), uint32(p2[0]), uint32(uint64(p3[0])>>32), uint32(uint64(p3[0])), uint32(uint64(p3[1])>>32), uint32(uint64(p3[1])), uint32(uint64(p3[2])>>32), uint32(uint64(p3[2])))
		return
	}
	gdextension.Host.Builtin.Types.SetupDictionary = func(p0 gdextension.Dictionary, p1 gdextension.VariantType, p2 gdextension.StringName, p3 gdextension.Variant, p4 gdextension.VariantType, p5 gdextension.StringName, p6 gdextension.Variant) {
		web_gd_variant_type_setup_dictionary(uint32(p0[0]), uint32(p1), uint32(p2[0]), uint32(uint64(p3[0])>>32), uint32(uint64(p3[0])), uint32(uint64(p3[1])>>32), uint32(uint64(p3[1])), uint32(uint64(p3[2])>>32), uint32(uint64(p3[2])), uint32(p4), uint32(p5[0]), uint32(uint64(p6[0])>>32), uint32(uint64(p6[0])), uint32(uint64(p6[1])>>32), uint32(uint64(p6[1])), uint32(uint64(p6[2])>>32), uint32(uint64(p6[2])))
		return
	}
	gdextension.Host.Builtin.Types.FetchConstant = func(p0 gdextension.VariantType, p1 gdextension.StringName, p2 gdextension.CallReturns[gdextension.Variant]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_type_fetch_constant(uint32(p0), uint32(p1[0]), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		return
	}
	gdextension.Host.Builtin.Types.Constructor = func(p0 gdextension.VariantType, p1 int) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_variant_type_unsafe_constructor(uint32(p0), int32(p1)))
		return
	}
	gdextension.Host.Builtin.Types.Evaluator = func(p0 gdextension.VariantOperator, p1 gdextension.VariantType, p2 gdextension.VariantType) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_variant_type_evaluator(uint32(p0), uint32(p1), uint32(p2)))
		return
	}
	gdextension.Host.Builtin.Types.Setter = func(p0 gdextension.VariantType, p1 gdextension.StringName) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_variant_type_setter(uint32(p0), uint32(p1[0])))
		return
	}
	gdextension.Host.Builtin.Types.Getter = func(p0 gdextension.VariantType, p1 gdextension.StringName) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_variant_type_getter(uint32(p0), uint32(p1[0])))
		return
	}
	gdextension.Host.Builtin.Types.HasProperty = func(p0 gdextension.VariantType, p1 gdextension.StringName) (result bool) {
		result = bool(0 != web_gd_variant_type_has_property(uint32(p0), uint32(p1[0])))
		return
	}
	gdextension.Host.Builtin.Types.Method = func(p0 gdextension.VariantType, p1 gdextension.StringName, p2 int64) (result gdextension.MethodForBuiltinType) {
		result = gdextension.MethodForBuiltinType(web_gd_variant_type_builtin_method(uint32(p0), uint32(p1[0]), uint32(uint64(p2)>>32), uint32(uint64(p2))))
		return
	}
	gdextension.Host.Builtin.Types.Unsafe.Call = func(p0 gdextension.CallMutates[interface{}], p1 gdextension.MethodForBuiltinType, p2 gdextension.CallReturns[interface{}], shape gdextension.Shape, p4 gdextension.CallAccepts[interface{}]) {
		mem0 := gdmemory.CopyReceiver(shape, p0)
		mem2 := gdmemory.MakeResult(shape)
		mem4 := gdmemory.CopyArguments(shape, p4)
		web_gd_variant_type_unsafe_call(uint32(mem0), uint32(p1), uint32(mem2), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem4))
		gdmemory.LoadResult(shape>>4, p0, mem0)
		gdmemory.LoadResult(shape, p2, mem2)
		return
	}
	gdextension.Host.Builtin.Types.Unsafe.Make = func(p0 gdextension.FunctionID, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_type_unsafe_make(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Builtin.Types.Unsafe.Free = func(p0 gdextension.VariantType, shape gdextension.Shape, p2 gdextension.CallAccepts[interface{}]) {
		mem2 := gdmemory.CopyArguments(shape, p2)
		web_gd_variant_type_unsafe_free(uint32(p0), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem2))
		return
	}
	gdextension.Host.Callables.Create = func(p0 gdextension.FunctionID, p1 gdextension.ObjectID, p2 gdextension.CallReturns[gdextension.Callable]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeCallable)
		web_gd_callable_create(uint32(p0), uint32(uint64(p1)>>32), uint32(uint64(p1)), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeCallable, p2, mem2)
		return
	}
	gdextension.Host.Callables.Lookup = func(p0 gdextension.Callable) (result gdextension.FunctionID) {
		result = gdextension.FunctionID(web_gd_callable_lookup(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1]))))
		return
	}
	gdextension.Host.ClassDB.FileAccess.Write = func(p0 gdextension.Object, p1 []byte) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		web_gd_classdb_FileAccess_write(uint32(p0), uint32(buf1), int32(len(p1)))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.ClassDB.FileAccess.Read = func(p0 gdextension.Object, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_classdb_FileAccess_read(uint32(p0), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.ClassDB.Image.Unsafe = func(p0 gdextension.Object) (result gdextension.Pointer) {
		result = gdextension.Pointer(web_gd_classdb_Image_unsafe(uint32(p0)))
		return
	}
	gdextension.Host.ClassDB.Image.Access = func(p0 gdextension.Object, p1 int) (result uint8) {
		result = uint8(web_gd_classdb_Image_access(uint32(p0), int32(p1)))
		return
	}
	gdextension.Host.ClassDB.MethodList.Make = func(p0 int) (result gdextension.MethodList) {
		result = gdextension.MethodList(web_gd_method_list_make(int32(p0)))
		return
	}
	gdextension.Host.ClassDB.MethodList.Push = func(p0 gdextension.MethodList, p1 gdextension.StringName, p2 gdextension.FunctionID, p3 gdextension.MethodFlags, p4 gdextension.PropertyList, p5 gdextension.PropertyList, p6 int, p7 gdextension.CallAccepts[gdextension.Variant]) {
		mem7 := gdmemory.CopyVariants(p7, p6)
		web_gd_method_list_push(uint32(p0), uint32(p1[0]), uint32(p2), uint32(p3), uint32(p4), uint32(p5), int32(p6), uint32(mem7))
		return
	}
	gdextension.Host.ClassDB.MethodList.Free = func(p0 gdextension.MethodList) {
		web_gd_method_list_free(uint32(p0))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Make = func(p0 int) (result gdextension.PropertyList) {
		result = gdextension.PropertyList(web_gd_property_list_make(int32(p0)))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Push = func(p0 gdextension.PropertyList, p1 gdextension.VariantType, p2 gdextension.StringName, p3 gdextension.StringName, p4 uint32, p5 gdextension.String, p6 uint32, p7 gdextension.ArgumentMetadata) {
		web_gd_property_list_push(uint32(p0), uint32(p1), uint32(p2[0]), uint32(p3[0]), uint32(p4), uint32(p5[0]), uint32(p6), uint32(p7))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Free = func(p0 gdextension.PropertyList) {
		web_gd_property_list_free(uint32(p0))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.Type = func(p0 gdextension.PropertyList) (result gdextension.VariantType) {
		result = gdextension.VariantType(web_gd_property_info_type(uint32(p0)))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.Name = func(p0 gdextension.PropertyList) (result gdextension.StringName) {
		result = gdextension.StringName{gdextension.Pointer(web_gd_property_info_name(uint32(p0)))}
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.ClassName = func(p0 gdextension.PropertyList) (result gdextension.StringName) {
		result = gdextension.StringName{gdextension.Pointer(web_gd_property_info_class_name(uint32(p0)))}
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.Hint = func(p0 gdextension.PropertyList) (result uint32) {
		result = uint32(web_gd_property_info_hint(uint32(p0)))
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.HinString = func(p0 gdextension.PropertyList) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_property_info_hint_string(uint32(p0)))}
		return
	}
	gdextension.Host.ClassDB.PropertyList.Info.Usage = func(p0 gdextension.PropertyList) (result uint32) {
		result = uint32(web_gd_property_info_usage(uint32(p0)))
		return
	}
	gdextension.Host.ClassDB.Register.Class = func(p0 gdextension.StringName, p1 gdextension.StringName, p2 gdextension.ExtensionClassID, p3 bool, p4 bool, p5 bool, p6 bool, p7 gdextension.String) {
		web_gd_classdb_register(uint32(p0[0]), uint32(p1[0]), uint32(p2), web_gd_bool(p3), web_gd_bool(p4), web_gd_bool(p5), web_gd_bool(p6), uint32(p7[0]))
		return
	}
	gdextension.Host.ClassDB.Register.Methods = func(p0 gdextension.StringName, p1 gdextension.MethodList) {
		web_gd_classdb_register_methods(uint32(p0[0]), uint32(p1))
		return
	}
	gdextension.Host.ClassDB.Register.Constant = func(p0 gdextension.StringName, p1 gdextension.StringName, p2 gdextension.StringName, p3 int64, p4 bool) {
		web_gd_classdb_register_constant(uint32(p0[0]), uint32(p1[0]), uint32(p2[0]), uint32(uint64(p3)>>32), uint32(uint64(p3)), web_gd_bool(p4))
		return
	}
	gdextension.Host.ClassDB.Register.Property = func(p0 gdextension.StringName, p1 gdextension.PropertyList, p2 gdextension.StringName, p3 gdextension.StringName) {
		web_gd_classdb_register_property(uint32(p0[0]), uint32(p1), uint32(p2[0]), uint32(p3[0]))
		return
	}
	gdextension.Host.ClassDB.Register.PropertyIndexed = func(p0 gdextension.StringName, p1 gdextension.PropertyList, p2 gdextension.StringName, p3 gdextension.StringName, p4 int) {
		web_gd_classdb_register_property_indexed(uint32(p0[0]), uint32(p1), uint32(p2[0]), uint32(p3[0]), int32(p4))
		return
	}
	gdextension.Host.ClassDB.Register.PropertyGroup = func(p0 gdextension.StringName, p1 gdextension.String, p2 gdextension.String) {
		web_gd_classdb_register_property_group(uint32(p0[0]), uint32(p1[0]), uint32(p2[0]))
		return
	}
	gdextension.Host.ClassDB.Register.PropertySubgroup = func(p0 gdextension.StringName, p1 gdextension.String, p2 gdextension.String) {
		web_gd_classdb_register_property_sub_group(uint32(p0[0]), uint32(p1[0]), uint32(p2[0]))
		return
	}
	gdextension.Host.ClassDB.Register.Signal = func(p0 gdextension.StringName, p1 gdextension.StringName, p2 gdextension.PropertyList) {
		web_gd_classdb_register_signal(uint32(p0[0]), uint32(p1[0]), uint32(p2))
		return
	}
	gdextension.Host.ClassDB.Register.Removal = func(p0 gdextension.StringName) {
		web_gd_classdb_register_removal(uint32(p0[0]))
		return
	}
	gdextension.Host.ClassDB.WorkerThreadPool.AddTask = func(p0 gdextension.Object, p1 gdextension.TaskID, p2 bool, p3 gdextension.String) {
		web_gd_classdb_WorkerThreadPool_add_task(uint32(p0), uint32(p1), web_gd_bool(p2), uint32(p3[0]))
		return
	}
	gdextension.Host.ClassDB.WorkerThreadPool.AddGroupTask = func(p0 gdextension.Object, p1 gdextension.TaskID, p2 int32, p3 int32, p4 bool, p5 gdextension.String) {
		web_gd_classdb_WorkerThreadPool_add_group_task(uint32(p0), uint32(p1), int32(p2), int32(p3), web_gd_bool(p4), uint32(p5[0]))
		return
	}
	gdextension.Host.ClassDB.XMLParser.Load = func(p0 gdextension.Object, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_classdb_XMLParser_load(uint32(p0), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Dictionaries.Get = func(p0 gdextension.Dictionary, p1 gdextension.Variant, p2 gdextension.CallReturns[gdextension.Variant]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_packed_dictionary_access(uint32(p0[0]), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		return
	}
	gdextension.Host.Dictionaries.Set = func(p0 gdextension.Dictionary, p1 gdextension.Variant, p2 gdextension.Variant) {
		web_gd_packed_dictionary_modify(uint32(p0[0]), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2])))
		return
	}
	gdextension.Host.Editor.AddDocumentation = func(p0 string) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		web_gd_editor_add_documentation(uint32(str0), int32(len(p0)))
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Editor.AddPlugin = func(p0 gdextension.StringName) {
		web_gd_editor_add_plugin(uint32(p0[0]))
		return
	}
	gdextension.Host.Editor.EndPlugin = func(p0 gdextension.StringName) {
		web_gd_editor_end_plugin(uint32(p0[0]))
		return
	}
	gdextension.Host.Iterators.Make = func(p0 gdextension.Variant, p1 gdextension.CallReturns[gdextension.Iterator], p2 gdextension.CallReturns[gdextension.CallError]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_iterator_make(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		gdmemory.LoadResult(gdextension.SizeVector3, p2, mem2)
		return
	}
	gdextension.Host.Iterators.Next = func(p0 gdextension.Variant, p1 gdextension.CallMutates[gdextension.Iterator], p2 gdextension.CallReturns[gdextension.CallError]) (result bool) {
		mem1 := gdmemory.CopyReceiver(gdextension.SizeVariant, p1)
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_iterator_next(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1), uint32(mem2)))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		gdmemory.LoadResult(gdextension.SizeVector3, p2, mem2)
		return
	}
	gdextension.Host.Iterators.Load = func(p0 gdextension.Variant, p1 gdextension.Iterator, p2 gdextension.CallReturns[gdextension.Variant], p3 gdextension.CallReturns[gdextension.CallError]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem3 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_iterator_load(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(mem2), uint32(mem3))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p3, mem3)
		return
	}
	gdextension.Host.Library.Location = func() (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_library_location())}
		return
	}
	gdextension.Host.Log.Error = func(p0 string, p1 string, p2 string, p3 string, p4 int32, p5 bool) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		str1 := gdmemory.CopyBufferToEngine([]byte(p1))
		str2 := gdmemory.CopyBufferToEngine([]byte(p2))
		str3 := gdmemory.CopyBufferToEngine([]byte(p3))
		web_gd_log_error(uint32(str0), int32(len(p0)), uint32(str1), int32(len(p1)), uint32(str2), int32(len(p2)), uint32(str3), int32(len(p3)), int32(p4), web_gd_bool(p5))
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		gdextension.Host.Memory.Free(gdextension.Pointer(str1))
		gdextension.Host.Memory.Free(gdextension.Pointer(str2))
		gdextension.Host.Memory.Free(gdextension.Pointer(str3))
		return
	}
	gdextension.Host.Log.Warning = func(p0 string, p1 string, p2 string, p3 string, p4 int32, p5 bool) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		str1 := gdmemory.CopyBufferToEngine([]byte(p1))
		str2 := gdmemory.CopyBufferToEngine([]byte(p2))
		str3 := gdmemory.CopyBufferToEngine([]byte(p3))
		web_gd_log_warning(uint32(str0), int32(len(p0)), uint32(str1), int32(len(p1)), uint32(str2), int32(len(p2)), uint32(str3), int32(len(p3)), int32(p4), web_gd_bool(p5))
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		gdextension.Host.Memory.Free(gdextension.Pointer(str1))
		gdextension.Host.Memory.Free(gdextension.Pointer(str2))
		gdextension.Host.Memory.Free(gdextension.Pointer(str3))
		return
	}
	gdextension.Host.Memory.Sizeof = func(p0 gdextension.StringName) (result int) {
		result = int(web_gd_memory_sizeof(uint32(p0[0])))
		return
	}
	gdextension.Host.Objects.Make = func(p0 gdextension.StringName) (result gdextension.Object) {
		result = gdextension.Object(web_gd_object_make(uint32(p0[0])))
		return
	}
	gdextension.Host.Objects.Call = func(p0 gdextension.Object, p1 gdextension.MethodForClass, p2 gdextension.CallReturns[gdextension.Variant], p3 int, p4 gdextension.CallAccepts[gdextension.Variant], p5 gdextension.CallReturns[gdextension.CallError]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem4 := gdmemory.CopyVariants(p4, p3)
		mem5 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_object_call(uint32(p0), uint32(p1), uint32(mem2), int32(p3), uint32(mem4), uint32(mem5))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p5, mem5)
		return
	}
	gdextension.Host.Objects.Name = func(p0 gdextension.Object) (result gdextension.StringName) {
		result = gdextension.StringName{gdextension.Pointer(web_gd_object_name(uint32(p0)))}
		return
	}
	gdextension.Host.Objects.Type = func(p0 gdextension.StringName) (result gdextension.ObjectType) {
		result = gdextension.ObjectType(web_gd_object_type(uint32(p0[0])))
		return
	}
	gdextension.Host.Objects.Cast = func(p0 gdextension.Object, p1 gdextension.ObjectType) (result gdextension.Object) {
		result = gdextension.Object(web_gd_object_cast(uint32(p0), uint32(p1)))
		return
	}
	gdextension.Host.Objects.Lookup = func(p0 gdextension.ObjectID) (result gdextension.Object) {
		result = gdextension.Object(web_gd_object_lookup(uint32(uint64(p0)>>32), uint32(uint64(p0))))
		return
	}
	gdextension.Host.Objects.Global = func(p0 gdextension.StringName) (result gdextension.Object) {
		result = gdextension.Object(web_gd_object_global(uint32(p0[0])))
		return
	}
	gdextension.Host.Objects.Extension.Setup = func(p0 gdextension.Object, p1 gdextension.StringName, p2 gdextension.ExtensionInstanceID) {
		web_gd_object_extension_setup(uint32(p0), uint32(p1[0]), uint32(p2))
		return
	}
	gdextension.Host.Objects.Extension.Fetch = func(p0 gdextension.Object) (result gdextension.ExtensionInstanceID) {
		result = gdextension.ExtensionInstanceID(web_gd_object_extension_fetch(uint32(p0)))
		return
	}
	gdextension.Host.Objects.Extension.Close = func(p0 gdextension.Object) {
		web_gd_object_extension_close(uint32(p0))
		return
	}
	gdextension.Host.Objects.ID.Get = func(p0 gdextension.Object, p1 gdextension.CallReturns[gdextension.ObjectID]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeInt)
		web_gd_object_id(uint32(p0), uint32(mem1))
		gdmemory.LoadResult(gdextension.SizeInt, p1, mem1)
		return
	}
	gdextension.Host.Objects.ID.InsideVariant = func(p0 gdextension.Variant, p1 gdextension.CallReturns[gdextension.ObjectID]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeInt)
		web_gd_object_id_inside_variant(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1))
		gdmemory.LoadResult(gdextension.SizeInt, p1, mem1)
		return
	}
	gdextension.Host.Objects.Method.Lookup = func(p0 gdextension.StringName, p1 gdextension.StringName, p2 int64) (result gdextension.MethodForClass) {
		result = gdextension.MethodForClass(web_gd_object_method_lookup(uint32(p0[0]), uint32(p1[0]), uint32(uint64(p2)>>32), uint32(uint64(p2))))
		return
	}
	gdextension.Host.Objects.Script.Make = func(p0 gdextension.ExtensionInstanceID) (result gdextension.ScriptInstance) {
		result = gdextension.ScriptInstance(web_gd_object_script_make(uint32(p0)))
		return
	}
	gdextension.Host.Objects.Script.Call = func(p0 gdextension.Object, p1 gdextension.StringName, p2 gdextension.CallReturns[gdextension.Variant], p3 int, p4 gdextension.CallAccepts[gdextension.Variant], p5 gdextension.CallReturns[gdextension.CallError]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem4 := gdmemory.CopyVariants(p4, p3)
		mem5 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_object_script_call(uint32(p0), uint32(p1[0]), uint32(mem2), int32(p3), uint32(mem4), uint32(mem5))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p5, mem5)
		return
	}
	gdextension.Host.Objects.Script.Setup = func(p0 gdextension.Object, p1 gdextension.ScriptInstance) {
		web_gd_object_script_setup(uint32(p0), uint32(p1))
		return
	}
	gdextension.Host.Objects.Script.Fetch = func(p0 gdextension.Object, p1 gdextension.Object) (result gdextension.ScriptInstance) {
		result = gdextension.ScriptInstance(web_gd_object_script_fetch(uint32(p0), uint32(p1)))
		return
	}
	gdextension.Host.Objects.Script.DefinesMethod = func(p0 gdextension.Object, p1 gdextension.StringName) (result bool) {
		result = bool(0 != web_gd_object_script_defines_method(uint32(p0), uint32(p1[0])))
		return
	}
	gdextension.Host.Objects.Script.AddPropertyState = func(p0 gdextension.FunctionID, p1 gdextension.Pointer, p2 gdextension.StringName, p3 gdextension.Variant) {
		web_gd_object_script_property_state_add(uint32(p0), uint32(p1), uint32(p2[0]), uint32(uint64(p3[0])>>32), uint32(uint64(p3[0])), uint32(uint64(p3[1])>>32), uint32(uint64(p3[1])), uint32(uint64(p3[2])>>32), uint32(uint64(p3[2])))
		return
	}
	gdextension.Host.Objects.Script.Placeholder.Create = func(p0 gdextension.Object, p1 gdextension.Object, p2 gdextension.Object) (result gdextension.ScriptInstance) {
		result = gdextension.ScriptInstance(web_gd_object_script_placeholder_create(uint32(p0), uint32(p1), uint32(p2)))
		return
	}
	gdextension.Host.Objects.Script.Placeholder.Update = func(p0 gdextension.ScriptInstance, p1 gdextension.Array, p2 gdextension.Dictionary) {
		web_gd_object_script_placeholder_update(uint32(p0), uint32(p1[0]), uint32(p2[0]))
		return
	}
	gdextension.Host.Objects.Unsafe.Free = func(p0 gdextension.Object) {
		web_gd_object_unsafe_free(uint32(p0))
		return
	}
	gdextension.Host.Packed.Bytes.Unsafe = func(p0 gdextension.PackedArray[uint8]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_byte_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Bytes.Access = func(p0 gdextension.PackedArray[uint8], p1 int) (result uint8) {
		pak0 := p0.JS()
		result = uint8(web_gd_packed_byte_array_access(pak0[0], pak0[1], int32(p1)))
		return
	}
	gdextension.Host.Packed.Colors.Unsafe = func(p0 gdextension.PackedArray[struct {
		R float32
		G float32
		B float32
		A float32
	}]) (result gdextension.Pointer) { pak0 := p0.JS(); result = gdextension.Pointer(web_gd_packed_color_array_unsafe(pak0[0], pak0[1])); return }
	gdextension.Host.Packed.Colors.Access = func(p0 gdextension.PackedArray[struct {
		R float32
		G float32
		B float32
		A float32
	}], p1 int, p2 gdextension.CallReturns[struct {
		R float32
		G float32
		B float32
		A float32
	}]) { pak0 := p0.JS(); mem2 := gdmemory.MakeResult(gdextension.SizeColor); web_gd_packed_color_array_access(pak0[0], pak0[1], int32(p1), uint32(mem2)); gdmemory.LoadResult(gdextension.SizeColor, p2, mem2); return }
	gdextension.Host.Packed.Float32s.Unsafe = func(p0 gdextension.PackedArray[float32]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_float32_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Float32s.Access = func(p0 gdextension.PackedArray[float32], p1 int) (result float32) {
		pak0 := p0.JS()
		result = float32(web_gd_packed_float32_array_access(pak0[0], pak0[1], int32(p1)))
		return
	}
	gdextension.Host.Packed.Float64s.Unsafe = func(p0 gdextension.PackedArray[float64]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_float64_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Float64s.Access = func(p0 gdextension.PackedArray[float64], p1 int) (result float64) {
		pak0 := p0.JS()
		result = float64(web_gd_packed_float64_array_access(pak0[0], pak0[1], int32(p1)))
		return
	}
	gdextension.Host.Packed.Int32s.Unsafe = func(p0 gdextension.PackedArray[int32]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_int32_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Int32s.Access = func(p0 gdextension.PackedArray[int32], p1 int) (result int32) {
		pak0 := p0.JS()
		result = int32(web_gd_packed_int32_array_access(pak0[0], pak0[1], int32(p1)))
		return
	}
	gdextension.Host.Packed.Int64s.Unsafe = func(p0 gdextension.PackedArray[int64]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_int64_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Int64s.Access = func(p0 gdextension.PackedArray[int64], p1 int, p2 gdextension.CallReturns[int64]) {
		pak0 := p0.JS()
		mem2 := gdmemory.MakeResult(gdextension.SizeInt)
		web_gd_packed_int64_array_access(pak0[0], pak0[1], int32(p1), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeInt, p2, mem2)
		return
	}
	gdextension.Host.Packed.Strings.Unsafe = func(p0 gdextension.PackedArray[gdextension.String]) (result gdextension.Pointer) {
		pak0 := p0.JS()
		result = gdextension.Pointer(web_gd_packed_string_array_unsafe(pak0[0], pak0[1]))
		return
	}
	gdextension.Host.Packed.Strings.Access = func(p0 gdextension.PackedArray[gdextension.String], p1 int) (result gdextension.String) {
		pak0 := p0.JS()
		result = gdextension.String{gdextension.Pointer(web_gd_packed_string_array_access(pak0[0], pak0[1], int32(p1)))}
		return
	}
	gdextension.Host.Packed.Vector2s.Unsafe = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
	}]) (result gdextension.Pointer) { pak0 := p0.JS(); result = gdextension.Pointer(web_gd_packed_vector2_array_unsafe(pak0[0], pak0[1])); return }
	gdextension.Host.Packed.Vector2s.Access = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
	}], p1 int, p2 gdextension.CallReturns[struct {
		X float32
		Y float32
	}]) { pak0 := p0.JS(); mem2 := gdmemory.MakeResult(gdextension.SizeVector2); web_gd_packed_vector2_array_access(pak0[0], pak0[1], int32(p1), uint32(mem2)); gdmemory.LoadResult(gdextension.SizeVector2, p2, mem2); return }
	gdextension.Host.Packed.Vector3s.Unsafe = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
		Z float32
	}]) (result gdextension.Pointer) { pak0 := p0.JS(); result = gdextension.Pointer(web_gd_packed_vector3_array_unsafe(pak0[0], pak0[1])); return }
	gdextension.Host.Packed.Vector3s.Access = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
		Z float32
	}], p1 int, p2 gdextension.CallReturns[struct {
		X float32
		Y float32
		Z float32
	}]) { pak0 := p0.JS(); mem2 := gdmemory.MakeResult(gdextension.SizeVariant); web_gd_packed_vector3_array_access(pak0[0], pak0[1], int32(p1), uint32(mem2)); gdmemory.LoadResult(gdextension.SizeVector3, p2, mem2); return }
	gdextension.Host.Packed.Vector4s.Unsafe = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
		Z float32
		W float32
	}]) (result gdextension.Pointer) { pak0 := p0.JS(); result = gdextension.Pointer(web_gd_packed_vector4_array_unsafe(pak0[0], pak0[1])); return }
	gdextension.Host.Packed.Vector4s.Access = func(p0 gdextension.PackedArray[struct {
		X float32
		Y float32
		Z float32
		W float32
	}], p1 int, p2 gdextension.CallReturns[struct {
		X float32
		Y float32
		Z float32
		W float32
	}]) { pak0 := p0.JS(); mem2 := gdmemory.MakeResult(gdextension.SizeVector4); web_gd_packed_vector4_array_access(pak0[0], pak0[1], int32(p1), uint32(mem2)); gdmemory.LoadResult(gdextension.SizeVector4, p2, mem2); return }
	gdextension.Host.RefCounted.Get = func(p0 gdextension.RefCounted) (result gdextension.Object) {
		result = gdextension.Object(web_gd_ref_get_object(uint32(p0)))
		return
	}
	gdextension.Host.RefCounted.Set = func(p0 gdextension.RefCounted, p1 gdextension.Object) {
		web_gd_ref_set_object(uint32(p0), uint32(p1))
		return
	}
	gdextension.Host.Strings.Access = func(p0 gdextension.String, p1 int) (result int32) {
		result = int32(web_gd_string_access(uint32(p0[0]), int32(p1)))
		return
	}
	gdextension.Host.Strings.Resize = func(p0 gdextension.String, p1 int) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_string_resize(uint32(p0[0]), int32(p1)))}
		return
	}
	gdextension.Host.Strings.Unsafe = func(p0 gdextension.String) (result gdextension.Pointer) {
		result = gdextension.Pointer(web_gd_string_unsafe(uint32(p0[0])))
		return
	}
	gdextension.Host.Strings.Append.String = func(p0 gdextension.String, p1 gdextension.String) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_string_append(uint32(p0[0]), uint32(p1[0])))}
		return
	}
	gdextension.Host.Strings.Append.Rune = func(p0 gdextension.String, p1 int32) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_string_append_rune(uint32(p0[0]), int32(p1)))}
		return
	}
	gdextension.Host.Strings.Decode.Latin1 = func(p0 string) (result gdextension.String) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.String{gdextension.Pointer(web_gd_string_decode_latin1(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Decode.UTF8 = func(p0 string) (result gdextension.String) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.String{gdextension.Pointer(web_gd_string_decode_utf8(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Decode.UTF16 = func(p0 string, p1 bool) (result gdextension.String) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.String{gdextension.Pointer(web_gd_string_decode_utf16(uint32(str0), int32(len(p0)), web_gd_bool(p1)))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Decode.UTF32 = func(p0 string) (result gdextension.String) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.String{gdextension.Pointer(web_gd_string_decode_utf32(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Decode.Wide = func(p0 string) (result gdextension.String) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.String{gdextension.Pointer(web_gd_string_decode_wide(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Encode.Latin1 = func(p0 gdextension.String, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_string_encode_latin1(uint32(p0[0]), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Strings.Encode.UTF8 = func(p0 gdextension.String, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_string_encode_utf8(uint32(p0[0]), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Strings.Encode.UTF16 = func(p0 gdextension.String, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_string_encode_utf16(uint32(p0[0]), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Strings.Encode.UTF32 = func(p0 gdextension.String, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_string_encode_utf32(uint32(p0[0]), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Strings.Encode.Wide = func(p0 gdextension.String, p1 []byte) (result int) {
		buf1 := gdmemory.CopyBufferToEngine(p1)
		result = int(web_gd_string_encode_wide(uint32(p0[0]), uint32(buf1), int32(len(p1))))
		gdmemory.CopyBufferToGo(buf1, p1)
		return
	}
	gdextension.Host.Strings.Intern.Latin1 = func(p0 string) (result gdextension.StringName) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.StringName{gdextension.Pointer(web_gd_string_intern_latin1(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Strings.Intern.UTF8 = func(p0 string) (result gdextension.StringName) {
		str0 := gdmemory.CopyBufferToEngine([]byte(p0))
		result = gdextension.StringName{gdextension.Pointer(web_gd_string_intern_utf8(uint32(str0), int32(len(p0))))}
		gdextension.Host.Memory.Free(gdextension.Pointer(str0))
		return
	}
	gdextension.Host.Threads.Main = func() (result bool) {
		result = bool(0 != web_gd_thread_is_main())
		return
	}
	gdextension.Host.Variants.Zero = func(p0 gdextension.CallReturns[gdextension.Variant]) {
		mem0 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_zero(uint32(mem0))
		gdmemory.LoadResult(gdextension.SizeVariant, p0, mem0)
		return
	}
	gdextension.Host.Variants.Copy = func(p0 gdextension.Variant, p1 gdextension.CallReturns[gdextension.Variant]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_copy(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		return
	}
	gdextension.Host.Variants.Call = func(p0 gdextension.Variant, p1 gdextension.StringName, p2 gdextension.CallReturns[gdextension.Variant], p3 int, p4 gdextension.CallAccepts[gdextension.Variant], p5 gdextension.CallReturns[gdextension.CallError]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem4 := gdmemory.CopyVariants(p4, p3)
		mem5 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_call(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(p1[0]), uint32(mem2), int32(p3), uint32(mem4), uint32(mem5))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p5, mem5)
		return
	}
	gdextension.Host.Variants.Eval = func(p0 gdextension.VariantOperator, p1 gdextension.Variant, p2 gdextension.Variant, p3 gdextension.CallReturns[gdextension.Variant]) (result bool) {
		mem3 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_variant_eval(uint32(p0), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2])), uint32(mem3)))
		gdmemory.LoadResult(gdextension.SizeVariant, p3, mem3)
		return
	}
	gdextension.Host.Variants.Hash = func(p0 gdextension.Variant, p1 gdextension.CallReturns[int64]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeInt)
		web_gd_variant_hash(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1))
		gdmemory.LoadResult(gdextension.SizeInt, p1, mem1)
		return
	}
	gdextension.Host.Variants.Bool = func(p0 gdextension.Variant) (result bool) {
		result = bool(0 != web_gd_variant_bool(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2]))))
		return
	}
	gdextension.Host.Variants.Text = func(p0 gdextension.Variant) (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_variant_text(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2]))))}
		return
	}
	gdextension.Host.Variants.Type = func(p0 gdextension.Variant) (result gdextension.VariantType) {
		result = gdextension.VariantType(web_gd_variant_type(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2]))))
		return
	}
	gdextension.Host.Variants.Deep.Copy = func(p0 gdextension.Variant, p1 gdextension.CallReturns[gdextension.Variant]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeVariant)
		web_gd_variant_deep_copy(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(mem1))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		return
	}
	gdextension.Host.Variants.Deep.Hash = func(p0 gdextension.Variant, p1 int, p2 gdextension.CallReturns[int64]) {
		mem2 := gdmemory.MakeResult(gdextension.SizeInt)
		web_gd_variant_deep_hash(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), int32(p1), uint32(mem2))
		gdmemory.LoadResult(gdextension.SizeInt, p2, mem2)
		return
	}
	gdextension.Host.Variants.Get.Index = func(p0 gdextension.Variant, p1 gdextension.Variant, p2 gdextension.CallReturns[gdextension.Variant]) (result bool) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_variant_get_index(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(mem2)))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		return
	}
	gdextension.Host.Variants.Get.Array = func(p0 gdextension.Variant, p1 int, p2 gdextension.CallReturns[gdextension.Variant], p3 gdextension.CallReturns[gdextension.CallError]) (result bool) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem3 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_variant_get_array(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), int32(p1), uint32(mem2), uint32(mem3)))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		gdmemory.LoadResult(gdextension.SizeVector3, p3, mem3)
		return
	}
	gdextension.Host.Variants.Get.Field = func(p0 gdextension.Variant, p1 gdextension.StringName, p2 gdextension.CallReturns[gdextension.Variant]) (result bool) {
		mem2 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_variant_get_field(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(p1[0]), uint32(mem2)))
		gdmemory.LoadResult(gdextension.SizeVariant, p2, mem2)
		return
	}
	gdextension.Host.Variants.Has.Index = func(p0 gdextension.Variant, p1 gdextension.Variant) (result bool) {
		result = bool(0 != web_gd_variant_has_index(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2]))))
		return
	}
	gdextension.Host.Variants.Has.Method = func(p0 gdextension.Variant, p1 gdextension.StringName) (result bool) {
		result = bool(0 != web_gd_variant_has_method(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(p1[0])))
		return
	}
	gdextension.Host.Variants.Set.Index = func(p0 gdextension.Variant, p1 gdextension.Variant, p2 gdextension.Variant) (result bool) {
		result = bool(0 != web_gd_variant_set_index(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2]))))
		return
	}
	gdextension.Host.Variants.Set.Array = func(p0 gdextension.Variant, p1 int, p2 gdextension.Variant, p3 gdextension.CallReturns[gdextension.CallError]) (result bool) {
		mem3 := gdmemory.MakeResult(gdextension.SizeVariant)
		result = bool(0 != web_gd_variant_set_array(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), int32(p1), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2])), uint32(mem3)))
		gdmemory.LoadResult(gdextension.SizeVector3, p3, mem3)
		return
	}
	gdextension.Host.Variants.Set.Field = func(p0 gdextension.Variant, p1 gdextension.StringName, p2 gdextension.Variant) (result bool) {
		result = bool(0 != web_gd_variant_set_field(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])), uint32(p1[0]), uint32(uint64(p2[0])>>32), uint32(uint64(p2[0])), uint32(uint64(p2[1])>>32), uint32(uint64(p2[1])), uint32(uint64(p2[2])>>32), uint32(uint64(p2[2]))))
		return
	}
	gdextension.Host.Variants.Unsafe.Call = func(p0 gdextension.FunctionID, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_call(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Variants.Unsafe.Eval = func(p0 gdextension.FunctionID, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_eval(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Variants.Unsafe.Free = func(p0 gdextension.Variant) {
		web_gd_variant_unsafe_free(uint32(uint64(p0[0])>>32), uint32(uint64(p0[0])), uint32(uint64(p0[1])>>32), uint32(uint64(p0[1])), uint32(uint64(p0[2])>>32), uint32(uint64(p0[2])))
		return
	}
	gdextension.Host.Variants.Unsafe.MakeNative = func(p0 gdextension.VariantType, p1 gdextension.Variant, shape gdextension.Shape, p3 gdextension.CallReturns[interface{}]) {
		mem3 := gdmemory.MakeResult(shape)
		web_gd_variant_unsafe_make_native(uint32(p0), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2])), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p3, mem3)
		return
	}
	gdextension.Host.Variants.Unsafe.FromNative = func(p0 gdextension.VariantType, p1 gdextension.CallReturns[gdextension.Variant], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(gdextension.SizeVariant)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_from_native(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(gdextension.SizeVariant, p1, mem1)
		return
	}
	gdextension.Host.Variants.Unsafe.InternalPointer = func(p0 gdextension.VariantType, p1 gdextension.Variant) (result gdextension.Pointer) {
		result = gdextension.Pointer(web_gd_variant_unsafe_internal_pointer(uint32(p0), uint32(uint64(p1[0])>>32), uint32(uint64(p1[0])), uint32(uint64(p1[1])>>32), uint32(uint64(p1[1])), uint32(uint64(p1[2])>>32), uint32(uint64(p1[2]))))
		return
	}
	gdextension.Host.Variants.Unsafe.Get.Field = func(p0 gdextension.FunctionID, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_get_field(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Variants.Unsafe.Get.Array = func(p0 gdextension.VariantType, p1 int, p2 gdextension.CallReturns[interface{}], shape gdextension.Shape, p4 gdextension.CallAccepts[interface{}]) {
		mem2 := gdmemory.MakeResult(shape)
		mem4 := gdmemory.CopyArguments(shape, p4)
		web_gd_variant_unsafe_get_array(uint32(p0), int32(p1), uint32(mem2), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem4))
		gdmemory.LoadResult(shape, p2, mem2)
		return
	}
	gdextension.Host.Variants.Unsafe.Get.Index = func(p0 gdextension.VariantType, p1 gdextension.CallReturns[interface{}], shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem1 := gdmemory.MakeResult(shape)
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_get_index(uint32(p0), uint32(mem1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		gdmemory.LoadResult(shape, p1, mem1)
		return
	}
	gdextension.Host.Variants.Unsafe.Set.Field = func(p0 gdextension.FunctionID, shape gdextension.Shape, p2 gdextension.CallAccepts[interface{}]) {
		mem2 := gdmemory.CopyArguments(shape, p2)
		web_gd_variant_unsafe_set_field(uint32(p0), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem2))
		return
	}
	gdextension.Host.Variants.Unsafe.Set.Array = func(p0 gdextension.VariantType, p1 int, shape gdextension.Shape, p3 gdextension.CallAccepts[interface{}]) {
		mem3 := gdmemory.CopyArguments(shape, p3)
		web_gd_variant_unsafe_set_array(uint32(p0), int32(p1), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem3))
		return
	}
	gdextension.Host.Variants.Unsafe.Set.Index = func(p0 gdextension.VariantType, shape gdextension.Shape, p2 gdextension.CallAccepts[interface{}]) {
		mem2 := gdmemory.CopyArguments(shape, p2)
		web_gd_variant_unsafe_set_index(uint32(p0), uint32(uint64(shape)>>32), uint32(uint64(shape)), uint32(mem2))
		return
	}
	gdextension.Host.Version.Major = func() (result uint32) {
		result = uint32(web_gd_version_major())
		return
	}
	gdextension.Host.Version.Minor = func() (result uint32) {
		result = uint32(web_gd_version_minor())
		return
	}
	gdextension.Host.Version.Patch = func() (result uint32) {
		result = uint32(web_gd_version_patch())
		return
	}
	gdextension.Host.Version.Hex = func() (result uint32) {
		result = uint32(web_gd_version_hex())
		return
	}
	gdextension.Host.Version.Status = func() (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_version_status())}
		return
	}
	gdextension.Host.Version.Build = func() (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_version_build())}
		return
	}
	gdextension.Host.Version.Hash = func() (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_version_hash())}
		return
	}
	gdextension.Host.Version.Timestamp = func(p0 gdextension.CallReturns[uint64]) {
		mem0 := gdmemory.MakeResult(gdextension.SizeRID)
		web_gd_version_timestamp(uint32(mem0))
		gdmemory.LoadResult(gdextension.SizeInt, p0, mem0)
		return
	}
	gdextension.Host.Version.String = func() (result gdextension.String) {
		result = gdextension.String{gdextension.Pointer(web_gd_version_string())}
		return
	}
}
